### ISSUE TITLE
Dumping Xdebug filter script requires resolving relative paths when phpunit.xml is not in root directory

### ISSUE THREAD

**Issue by localheinz** [sebastianbergmann/phpunit#3482] opened 2019-01-15 07:56 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.1
| PHP version         | 7.1.24
| Installation Method | Composer

### `test/Unit/phpunit.xml`

```xml
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../vendor/phpunit/phpunit/phpunit.xsd"
    bootstrap="../../vendor/autoload.php"
>
    <testsuites>
        <testsuite name="Unit Tests">
            <directory>.</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist addUncoveredFilesFromWhitelist="true" processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">../../src</directory>
        </whitelist>
    </filter>
</phpunit>
```

### `Makefile`

```Make
.PHONY: coverage

coverage: vendor
	vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --dump-xdebug-filter .build/phpunit/xdebug-filter.php
	vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-text --prepend .build/phpunit/xdebug-filter.php

vendor: composer.json composer.lock
	composer validate
	composer install
```

When I run

```
$ make coverage
```

I end up with

```
vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --dump-xdebug-filter .build/phpunit/xdebug-filter.php
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.25 with Xdebug 2.6.1
Random seed:   1547538628
Configuration: /Users/am/Sites/localheinz/json-normalizer/test/Unit/phpunit.xml

Wrote Xdebug filter script to .build/phpunit/xdebug-filter.php
vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-text --prepend .build/phpunit/xdebug-filter.php
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.25 with Xdebug 2.6.1
Random seed:   1547538629
Configuration: /Users/am/Sites/localheinz/json-normalizer/test/Unit/phpunit.xml

........................................................................................................................................................................................................................................................................................                      280 / 280 (100%)

Time: 781 ms, Memory: 22.00MB

OK (280 tests, 558 assertions)


Code Coverage Report:
  2019-01-15 07:50:28

 Summary:
  Classes:  0.00% (0/30)
  Methods:  0.00% (0/85)
  Lines:    0.00% (0/578)
```

### `.build/phpunit/xdebug-filter.php`

The generated filter script looks like this:

```php
<?php declare(strict_types=1);
if (!\function_exists('xdebug_set_filter')) {
    return;
}

\xdebug_set_filter(
    \XDEBUG_FILTER_CODE_COVERAGE,
    \XDEBUG_PATH_WHITELIST,
    [
        '/Users/am/Sites/localheinz/json-normalizer/test/Unit/../../src'
    ]
);
```

When I modify it to 

```diff
diff --git a/.build/phpunit/xdebug-filter.php b/.build/phpunit/xdebug-filter.php
index ec45a4e..1f5a3bd 100644
--- a/.build/phpunit/xdebug-filter.php
+++ b/.build/phpunit/xdebug-filter.php
@@ -7,6 +7,6 @@ if (!\function_exists('xdebug_set_filter')) {
     \XDEBUG_FILTER_CODE_COVERAGE,
     \XDEBUG_PATH_WHITELIST,
     [
-        '/Users/am/Sites/localheinz/json-normalizer/test/Unit/../../src'
+        '/Users/am/Sites/localheinz/json-normalizer/src'
     ]
 );
```

and disable filter script generation and then run

```
$ make coverage
```

again it works as expected, resulting in

```
vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-text --prepend .build/phpunit/xdebug-filter.php
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.25 with Xdebug 2.6.1
Random seed:   1547539140
Configuration: /Users/am/Sites/localheinz/json-normalizer/test/Unit/phpunit.xml

........................................................................................................................................................................................................................................................................................                      280 / 280 (100%)

Time: 974 ms, Memory: 24.00MB

OK (280 tests, 558 assertions)


Code Coverage Report:
  2019-01-15 07:59:00

 Summary:
  Classes: 100.00% (30/30)
  Methods: 100.00% (85/85)
  Lines:   100.00% (334/334)

...
```

That is, the only issue here is that the path needs to be resolved properly, perhaps using `realpath()`, when generating the filter script.

For a full example, see https://github.com/localheinz/json-normalizer/pull/124.

**Comment by sebastianbergmann** [comment] 2019-01-15 08:09
Are you sure this is not a duplicate of #3456?

**Comment by localheinz** [comment] 2019-01-15 08:16
@sebastianbergmann 

Ha, you are right, it is a duplicate of #3456.

Thank you!

**Closed** 2019-01-19 09:10 UTC
