### ISSUE TITLE
Loading XML files with specific entity definitions would fail

### ISSUE THREAD

**Issue by gundamew** [sebastianbergmann/phpunit#5672] opened 2024-01-17 15:02 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.7
| PHP version         | 8.2.14
| Installation Method | Composer

#### Summary

Loading XML files with PHPUnit 10 would fail if they contain specific entity definitions. Converting the entities into parameter entities can resolve this issue.

* Passed `<!ENTITY % name value>`
* Failed `<!ENTITY name value>`

| name | value  |           |
|-------|---------|-----------|
| amp   | `&#38;`  | ❌ invalid |
| amp   | `&amp;`  | ❌ invalid |
| apos  | `&#39;`  | ⭕️ valid  |
| apos  | `&apos;` | ❌ invalid |
| gt    | `&#62;`  | ⭕️ valid  |
| gt    | `&gt;`   | ❌ invalid |
| lt    | `&#60;`  | ❌ invalid |
| lt    | `&lt;`   | ❌ invalid |
| quot  | `&#34;`  | ⭕️ valid  |
| quot  | `&quot;` | ❌ invalid |

The libxml version is 2.9.14.

```shell
$ php --info | grep 'libxml'
libxml Version => 2.9.14
libxml
libxml2 Version => 2.9.14
```

The issue seems related to **libxml**, but this didn't answer why it didn't happen to PHPUnit 9.

Thanks to the senior developer of my team, [Albert Wang](https://tw.linkedin.com/in/albert-wang-59357095), for helping me verify this issue.

#### Current behavior

It would throw a `xmlAddEntity: invalid redeclaration of predefined entity` error.

#### How to reproduce

Here is the sample repository: https://github.com/gundamew/phpunit10-xml-file-loading-issue

There are 1 unit test with 3 sample XML files.

1. Clone it.
2. Switch to `phpunit9` or `phpunit10` branch.
3. Run `composer install`.
4. Run `./vendor/bin/phpunit -c ./phpunit.xml`.

#### Expected behavior

Test passed.

**Comment by marac19901990** [comment] 2024-01-17 16:55
@gundamew I checked this and as far as i see: 
  - It says you cannot redeclare entity because it is already declared (don't see any issue with that), just dont redeclare entity and use it, since it is already inbuilt, for the ones that aren't you can create them.

@sebastianbergmann I think you can close this.

**Comment by theseer** [comment] 2024-01-18 14:02
## Short answer

The observed behavior of PHPUnit 10 is correct, your XML + entity definition is simply invalid. This is not a bug in PHPUnit.

## Longer answer

According to the [XML Standard](https://www.w3.org/TR/xml/#sec-predefined-ent), the following entities are "predefined" (read: implicitly defined by the XML processor):

```
<!ENTITY lt     "&#38;#60;">
<!ENTITY gt     "&#62;">
<!ENTITY amp    "&#38;#38;">
<!ENTITY apos   "&#39;">
<!ENTITY quot   "&#34;">
```

The observed behavior shown in the table is indeed confusing: Assuming I understand the W3C spec correctly, re-declaring any of the aforementioned entities should *not* be a problem. It's actually contradicting the side note that for interoperability, one should do that very thing. I would also understand a consistent refusal from LibXML to re-declare *any* of them, even though that would likely qualify as a violation of the W3C spec. Wouldn't be the first one though. Either way, LibXML is behaving inconsistently depending on the entity re-declared. 

We could consider opening an issue with the LibXML developers or even PHP `ext/dom` as we're using it as our direct upstream provider. (ping /cc @nielsdos).


With regards to the observed behavior of PHPUnit 9 vs. 10:

The re-declaration fails in both versions. It's merely a warning though, the document gets actually loaded. In PHPUnit 9, we had the option to be less strict - which was the default - when loading or parsing XML data, effectively hiding any of these errors. With PHPUnit 10 this (dangerously missleading) behavior has been removed.


### Summary

Your XML is invalid - at least when processed with LibXML. PHPUnit 9 as well as PHPUnit 10 notice that. The only difference is that PHPUnit 9 swallowed the warnings emitted whereas PHPUnit 10 (correctly) barks.

___This is not a bug in PHPUnit.___

**Closed by theseer** 2024-01-18 14:02 UTC
Labels: type/bug, version/10

**Comment by gundamew** [comment] 2024-01-18 14:42
First, thank you for investing time in this issue, @marac19901990, and @theseer.

I found this problem in migrating PHPUnit from 9 to 10 for production code. Yes, the XML is invalid, but I can't change the XML file contents for some reason. So I came here to find out if I can resolve it on the PHPUnit side. Now I know what I should do to fix it.

Thank you again for your detailed answer, @theseer. And thank you, @marac19901990, for your prompt reply.

**Comment by nielsdos** [comment] 2024-01-18 19:55
> We could consider opening an issue with the LibXML developers or even PHP ext/dom as we're using it as our direct upstream provider. (ping /cc @nielsdos).

> Either way, LibXML is behaving inconsistently depending on the entity re-declared.

The custom declaration of a predefined entity must match the spec's.
So the behaviour specified by the table seems correct to me.
I don't see the inconsistency (note the rule for double encoding being required for lt an amp)?

**Comment by theseer** [comment] 2024-01-18 21:37
> > We could consider opening an issue with the LibXML developers or even PHP ext/dom as we're using it as our direct upstream provider. (ping /cc @nielsdos).
> 
> > Either way, LibXML is behaving inconsistently depending on the entity re-declared.
> 
> The custom declaration of a predefined entity must match the spec's. So the behaviour specified by the table seems correct to me. I don't see the inconsistency (note the rule for double encoding being required for < and &)?

Thanks for the clarification. You're - of course - perfectly right. I indeed missed the requirement for it being identical. So, no bug at all then. Even better :-)
