### ISSUE TITLE
Tests stop running without any message

### ISSUE THREAD

**Issue by Cafnio** [sebastianbergmann/phpunit#2736] opened 2017-07-12 09:14 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 5.7.12
| PHP version         | 5.6.10
| Installation Method | Composer / PHAR

Hi there.

I'm creating tests for controllers I have on my cakephp 3.4 Project. I'm also using Mac with 10.12.5 So far, it's going good, but i'm having a problem that I can't find a solution.

Here's my code from the test:

```
public function testNewPassword(){

        $this->get('/users/newPassword');
        $expected = [
            'controller' => 'Activities',
            'action' => 'index',
        ];
        $this->assertSession(__('O URL que tentou abrir não foi encontrado. Se está a tentar recuperar a password, tente recuperá-la novamente através da página "Recuperar Password". '), 'Flash.flash.0.message');
        $this->assertRedirect($expected);

        $this->post('/users/newPassword', [
            'token' => 'nverfoundgmailcom',
            'hash' => "",
            'password' => ''
        ]);
        $expected = [
            'controller' => 'Users',
            'action' => 'newPassword',
        ];
        $this->assertRedirect($expected);
    }

```

and here's the fuction NewPassword on my controller:

```
public function newPassword($token = null){
        ini_set('display_errors', 1);
        ini_set('display_startup_errors', 1);
        error_reporting(E_ALL);
        if($this->authUser != null){
            $this->Auth->logout();
            $this->Cookie->delete('remember_session');
            $this->Cookie->delete('user');
            $this->Cookie->write('destroylogin', 1);
            $this->session->destroy();
            return $this->redirect(['action' => 'newPassword', $token]);
        }
        if ($this->request->is('post')) {
            if ($this->request->data['token'] == $this->session->read('Form')){
                $this->Flash->success(__('Palavra-passe alterada com sucesso.'), [
                    'clear' => true,
                ]);
                return $this->redirect(['controller' => '/']);
            }
            var_dump("0");
            $user = $this->Users->find('all', array('conditions' => array('password_token' => $this->request->data['token'])))->first();
            var_dump("1");
            if ($user != null){
                $this->Users->patchEntity($user, ['password' => $this->request->data['password'], 'password_timestamp' => NULL, 'password_token' => NULL]);
                if($user->activated==0){
                    $user->activated = 1;
                }
                if ($this->Users->save($user)){
                    $this->session->write('Form', $this->request->data['token']);
                    $this->Flash->success(__('Palavra-passe alterada com sucesso.'), [
                        'clear' => true,
                    ]);
                    return $this->redirect(['controller' => '/']);
                }
            }
            $this->Flash->error(__('Ocorreu um erro, tenta novamente.'), [
                'clear' => true,
            ]);
            return $this->redirect(['action' => 'newPassword', $token]);
        }
        if($token == null){
            $this->Flash->error(__('O URL que tentou abrir não foi encontrado. Se está a tentar recuperar a password, tente recuperá-la novamente através da página "Recuperar Password". '), [
                'clear' => true,
            ]);
            return $this->redirect(['controller' => 'Activities', 'action' => 'index']);
        }
        $user = $this->Users->find('all', ['conditions' => ['password_token' => $token, 'password_timestamp >= DATE_SUB(NOW(), INTERVAL 1 DAY)']])->count();
        if ($user == 0){
            $this->Flash->error(__('O URL que tentou abrir não foi encontrado. Se está a tentar recuperar a password, tente recuperá-la novamente através da página "Recuperar Password". '), [
                'clear' => true,
            ]);
            return $this->redirect(['controller' => '/']);
        }
        $this->set('token', $token);
    }

```

The problem i'm finding is that on my cmd, it's print's out the var_dump("0"), but after that, it exits on the find Function, right after it, so the var_dump("1") doesn't show on it. Also, it doens't show any quit errors or nothing.

Here's my phpunit.xml file

```<?xml version="1.0" encoding="UTF-8"?>
<phpunit
	colors="true"
	processIsolation="false"
	stopOnFailure="false"
	syntaxCheck="false"
	bootstrap="./tests/bootstrap.php"
	convertErrorsToExceptions="true"
	convertNoticesToExceptions="true"
	convertWarningsToExceptions="true"
	stopOnError="false"
	stopOnIncomplete="false"
	stopOnSkipped="false"
	strict="false"
	verbose="true"
	>
	<php>
		<ini name="memory_limit" value="-1"/>
		<ini name="apc.enable_cli" value="1"/>
		<ini name="display_errors" value="true"/>
	</php>

	<!-- Add any additional test suites you want to run here -->
	<testsuites>
		<testsuite name="App Test Suite">
			<!--<directory>./tests/TestCase</directory>-->
			<file>tests/Testcase/Model/Table/UsersTableTest.php</file>
			<file>tests/Testcase/Controller/UsersControllerTest.php</file>
			<file>tests/Testcase/Model/Table/InstitutionsTableTest.php</file>
		</testsuite>
		<!-- Add plugin test suites here. -->
	</testsuites>

	<!-- Setup a listener for fixtures -->
	<listeners>
		<listener
		class="\Cake\TestSuite\Fixture\FixtureInjector"
		file="./vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php">
			<arguments>
				<object class="\Cake\TestSuite\Fixture\FixtureManager" />
			</arguments>	
		</listener>
	</listeners>

</phpunit>
```

**Comment by sebastianbergmann** [comment] 2017-07-12 09:45
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by Cafnio** [comment] 2017-07-12 09:46
Hi there.

Thanks for the fast answer.

How can I provide that?

Thanks

**Comment by Cafnio** [comment] 2017-07-12 12:16
Founded the origin of the problem.

Had two problems on my mysql connection, and that was making it getting broken:
-> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`common_resources_test`.`users`, CONSTRAINT `fk_users_cities` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE)
->"SQLSTATE[08004] [1040] Too many connections"

I've discoreved it by doing some try catches and finding hte problem on the exception.

Is there any way that can Phpunit list this errors?

**Comment by sebastianbergmann** [comment] 2017-07-12 14:22
PHPUnit would show these exceptions by default. If it does not then because the exceptions are handled, either explicitly by `catch`ing them or implicitly through an exception handler.

I am closing this issue as it does not appear to be related to PHPUnit.

**Closed by sebastianbergmann** 2017-07-12 14:22 UTC
