### ISSUE TITLE
Fatal error caused by undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration()

### ISSUE THREAD

**Issue by gabrielkaputa** [sebastianbergmann/phpunit#2434] opened 2017-01-24 08:42 UTC
hi, i'm having an issue with one of my projects, this is the response i'm getting. could somebody help me how to move forward with this? thanks!

it's phpunit 5.7.6

```
$ phpunit
PHP Fatal error:  Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in /home/travis/build/gabrielkaputa/bitly/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 1042
PHP Stack trace:
PHP   1. {main}() /home/travis/.phpenv/versions/5.6.5/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/.phpenv/versions/5.6.5/bin/phpunit:722
PHP   3. PHPUnit_TextUI_Command->run() 
phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:104
PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:152
PHP   5. PHPUnit_TextUI_TestRunner->handleConfiguration() /home/travis/build/gabrielkaputa/bitly/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:163
```

**Comment by sebastianbergmann** [comment] 2017-01-24 08:57
Duplicate of #2432.

**Closed by sebastianbergmann** 2017-01-24 08:57 UTC

**Comment by prashantidealittechno** [comment] 2017-05-03 05:44
I had the same error and i run new command. Try to run  the command ```vendor/bin/phpunit``` and it will work.

**Comment by chisumo2016** [comment] 2017-08-22 16:21
tal error: Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1066
Stack trace:
#0 C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(163): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1066

C:\laragon\www\forum-tdd-apps>phpunit
PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1066
Stack trace:
#0 C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(163): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1066

Fatal error: Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1066
Stack trace:
#0 C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(163): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in C:\laragon\www\forum-tdd-apps\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1066

**Comment by yamenarahman** [comment] 2018-09-04 16:34
For any who is experiencing this, `vendor/bin/phpunit` definitely works but you might want to install phpunit with composer globally to solve this.

**Comment by denisdulici** [comment] 2018-09-28 09:44
For Windows, if you don't add PATH, this one works `vendor\bin\phpunit`
