### ISSUE TITLE
The stable version of phpunit depends on an abandoned package

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/phpunit#4717] opened 2021-06-22 10:24 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.5
| PHP version         | 7.4.12
| Installation Method | Composer

#### Summary

PHPUnit 9.5 depends on the `sebastian/resource-operations` package (developed in https://github.com/sebastianbergmann/resource-operations) which has been marked as abandoned on Packagist. this means that composer shows a warning about an abandoned package for all users of PHPUnit installing it through composer.

#### How to reproduce

Install PHPUnit through composer and read the composer output

#### Expected behavior

Marking the package as abandoned should probably be delayed until the release of PHPUnit 10 (assuming it does not use it anymore)

**Comment by sebastianbergmann** [comment] 2021-06-22 10:29
Duplicate of #4714.

**Closed by sebastianbergmann** 2021-06-22 10:29 UTC
Labels: type/bug

**Comment by stof** [comment] 2021-06-22 10:32
hmm indeed. I missed this closed issue. The fact that we need to ignore a warning is quite unfortunate, as users won't know about that until they report it (or they find the closed issues already reporting it).
Why not waiting until the PHPunit 10 release to mark it abandoned on packagist instead ?
