### ISSUE TITLE
Self update leaves empty files behind

### ISSUE THREAD

**Issue by it-can** [sebastianbergmann/phpunit#1974] opened 2015-11-30 09:35 UTC
When I do a ```phpunit --self-update``` it will leave an empty file behind in the tmp folder, is this necessary?

**Comment by sebastianbergmann** [comment] 2016-02-22 21:13
I can reproduce this behavior and agree that it is not nice. I have no idea what is going on here.

However, I will close this since the feature in question will be removed in the future (see #2088).

**Closed by sebastianbergmann** 2016-02-22 21:13 UTC
