### ISSUE TITLE
Fatal error: Cannot use PHPUnit\Framework\MockObject\Invocation as Invocation because the name is already in use in C:\wamp64\www\unit\vendor\phpunit\phpunit-mock-objects\src\Matcher\MethodName.php on line 14

### ISSUE THREAD

**Issue by misyaath** [sebastianbergmann/phpunit#2910] opened 2017-12-08 17:58 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5
| PHP version         | 7.0.0
| Installation Method | Composer / PHAR

````

$this->formatter = $this->getMockBuilder( "TDD\Formatter" )
            ->setMethods( [ 'currencyAmt' ] )
            ->getMock();

        $this->formatter->expects( $this->any() )
            ->method( 'currencyAmt' )
            ->with( $this->anything() )
            ->will( $this->returnArgument( 0 ) );

```

PHPUnit 6.5.3 by Sebastian Bergmann and contributors.

........
Fatal error: Cannot use PHPUnit\Framework\MockObject\Invocation as Invocation because the name is already in use in C:\wamp64\www\unit\vendor\phpunit\phpunit-mock-objects\src\Matcher\MethodName.php on line 14

**Comment by sebastianbergmann** [comment] 2017-12-09 06:14
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Comment by sebastianbergmann** [comment] 2017-12-09 06:15
That being said, I cannot reproduce the issue:
```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $this->formatter = $this->getMockBuilder( 'TDD\Formatter' )
                                ->setMethods( [ 'currencyAmt' ] )
                                ->getMock();

        $this->formatter->expects( $this->any() )
             ->method( 'currencyAmt' )
             ->with( $this->anything() )
             ->will( $this->returnArgument( 0 ) );

        $this->assertEquals('foo', $this->formatter->currencyAmt('foo'));
    }
}
```
```
$ phpunit Test
PHPUnit 6.5.3 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 23 ms, Memory: 4.00MB

OK (1 test, 1 assertion)
```

**Closed by sebastianbergmann** 2017-12-09 06:14 UTC

**Comment by misyaath** [comment] 2017-12-09 06:42
It was working perfectly after some time when i run it cause above error I can't figured it out Only it happens when i use` ->method('Mehtod mname');`

Here its my code 

```
<?php
namespace TDD\Tests;
require dirname( dirname( __FILE__ ) ) . DIRECTORY_SEPARATOR . "vendor" . DIRECTORY_SEPARATOR . "autoload.php";
use PHPUnit\Framework\TestCase;
use TDD\Receipt;

class ReceiptTest extends TestCase
{

    public function setUp()
    {
        $this->formatter = $this->getMockBuilder( 'TDD\Formatter' )
            ->setMethods( [ 'currencyAmt' ] )
            ->getMock();

        $this->formatter->expects( $this->any() )
            ->method( 'currencyAmt' )
            ->with( $this->anything() )
            ->will( $this->returnArgument( 0 ) );

        $this->assertEquals( 'foo', $this->formatter->currencyAmt( 'foo' ) );

        $this->receipt = new Receipt();
    }

    public function tearDown()
    {
        unset( $this->receipt );
        unset( $this->formatter );
    }

    /**
     * @dataProvider provideTotal
     */

    public function testTotal( $items, $expected )
    {
        $coupon = null;
        $output = $this->receipt->total( $items, $coupon );

        $this->assertEquals(
            $expected,
            $output,
            "When Summing should Equal {$expected}"
        );
    }

    public function provideTotal()
    {
        return [
            "ins totaling 16" => [ [ 0, 2, 5, 8 ], 15 ],
            [ [ -1, 2, 5, 8 ], 14 ],
            [ [ 1, 2, 8 ], 11 ],
        ];
    }

    public function testTotalAndCoupon()
    {
        $input = array( 0, 2, 5, 8 );
        $coupon = 0.20;
        $output = $this->receipt->total( $input, $coupon );

        $this->assertEquals(
            12,
            $output,
            "When Summing should Equal 12"
        );
    }

    public function testPostTaxTotal()
    {
        $items = array( 0, 2, 5, 8 );
        $tax = 0.20;
        $coupon = null;
        $receipt = $this->getMockBuilder( "TDD\Receipt" )
            ->setMethods( array( "tax", "total" ) )
            ->getMock();

        $receipt->expects( $this->once() )
            ->method( "total" )
            ->with( $items, $coupon )
            ->will( $this->returnValue( 10.00 ) );

        $receipt->expects( $this->once() )
            ->method( "tax" )
            ->with( 10.00, $tax )
            ->will( $this->returnValue( 1.00 ) );

        $result = $receipt->postTaxTotal( array( 0, 2, 5, 8 ), 0.20, null );
        $this->assertEquals( 11.00, $result );
    }

    public function testTax()
    {
        $input = 10.0;
        $taxInput = 0.10;
        $output = $this->receipt->tax( $input, $taxInput );

        $this->assertEquals( 1, $output, "Tax must equal to 1.0" );
    }
}
```

**Comment by sebastianbergmann** [comment] 2017-12-09 11:47
Please open a new ticket and provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.
