### ISSUE TITLE
[Fatal error] Class phpDocumentor\Reflection\DocBlock\Tags\Example

### ISSUE THREAD

**Issue by JercSi** [sebastianbergmann/phpunit#2207] opened 2016-06-09 08:45 UTC
I have problems with version 5.4.3. I can't run any test, help, print version,...
Version 5.4.2 is OK.
PHP: 7.0.6

`php phpunit-5.4.3.phar -v`

```
PHP Fatal error:  Class phpDocumentor\Reflection\DocBlock\Tags\Example contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (phpDocumentor\Reflection\DocBlock\Tag::__toString) in phar://D:/dev/PHPUnit/phpunit-5.4.3.phar/phpdocumentor-reflection-docblock/DocBlock/Tags/Example.php on line 148
PHP Stack trace:
PHP   1. {main}() D:\dev\PHPUnit\phpunit-5.4.3.phar:0

Fatal error: Class phpDocumentor\Reflection\DocBlock\Tags\Example contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (phpDocumentor\Reflection\DocBlock\Tag::__toString) in phar://D:/dev/PHPUnit/phpunit-5.4.3.phar/phpdocumentor-reflection-docblock/DocBlock/Tags/Example.php on line 148

Call Stack:
    0.0160     810672   1. {main}() D:\dev\PHPUnit\phpunit-5.4.3.phar:0
```

**Comment by sebastianbergmann** [comment] 2016-06-09 08:45
Duplicate of #2206

**Closed by sebastianbergmann** 2016-06-09 08:45 UTC
