### ISSUE TITLE
Assert-message manipulated?!

### ISSUE THREAD

**Issue by luklapp** [sebastianbergmann/phpunit#1811] opened 2015-08-04 12:49 UTC
The assert-message seems to be manipulated by phpunit. I am searching in a string (html) and found the following:

`Failed asserting that '<div class="error">Product: ID is not invalid</div>' does not contain 'error'.`

The correct error message is: `<div class="error">Product: ID is invalid</div>`. Is it possible that *is* is replaced by *is not*? I was very confused about this error message ;-)

**Comment by sebastianbergmann** [comment] 2015-08-04 13:21
Duplicate of #764.

**Closed by sebastianbergmann** 2015-08-04 13:21 UTC
