### ISSUE TITLE
Exception "This build of PHPDBG does not support code coverage"

### ISSUE THREAD

**Issue by drewblin** [sebastianbergmann/phpunit#4212] opened 2020-05-08 14:47 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.1.4
| PHP version         | 7.4.1
| Installation Method | PHAR

#### Summary

I'm getting error "This build of PHPDBG does not support code coverage" when try to run phpunit with coverage with phpdbg. I found in PHAR line which generate this error:
```
        if (!\function_exists('PHPUnit\\phpdbg_start_oplog')) {
            throw new \PHPUnit\SebastianBergmann\CodeCoverage\RuntimeException('This build of PHPDBG does not support code coverage');
        }
```

Then i run and get this result:
```
prompt> ev function_exists('phpdbg_start_oplog');
1
```

As i undestand, problem is in namespace before phpdbg_start_oplog. So, why phpdbg_start_oplog is prefixed with PHPUnit namespace in PHAR?

#### Current behavior

Exception "This build of PHPDBG does not support code coverage"

#### How to reproduce

Run in console
```
phpdbg -qrr ./phpunit --coverage-html build/coverage-report ./XTest.php
```

Where XTest.php is
```
<?php

class XTest extends \PHPUnit\Framework\TestCase
{
        public function test()
        {
        }
}
```

#### Expected behavior

No exception

**Comment by sebastianbergmann** [comment] 2020-05-08 14:49
Duplicate of #4211.

**Closed by sebastianbergmann** 2020-05-08 14:49 UTC
Labels: type/bug
