### ISSUE TITLE
Emit warning for problematic opcache configurations

### ISSUE THREAD

**Issue by Danack** [sebastianbergmann/phpunit#1596] opened 2015-01-30 23:15 UTC
I'm trying to test the Amazon AWS sdk. Testing it works fine on OSX works fine, testing inside a vagrant box seems to fail massively.

To run the tests, I'm running the commands:

```
git clone https://github.com/aws/aws-sdk-php
cd aws-sdk-php/
composer -d allow_url_fopen=1 update
php vendor/bin/phpunit
```

For both PHP 5.6.2. and PHP 7 the output looks like:

![PHPUnit output](http://i.stack.imgur.com/s4x7z.png)

Not only are the tests failing, but the output seems corrupted with some output of the tests interleaved with the output of the test status. 

I haven't seen anything like this before; I can run PHPUnit tests for other projects inside the VM without any problem, but they are using older versions of PHPUnit.

The box being used is: http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box If necessary I could provide a vagrant conf file.

**Comment by whatthejeff** [comment] 2015-01-31 00:24
Probably better to ask the AWS team, but this looks like expected behavior. Seems their integration tests log these messages to `stderr`. If you redirect `stderr` elsewhere, the output should look normal.

**Comment by Danack** [comment] 2015-01-31 01:20
@whatthejeff yeah, I've pinged @mtdowling and he's now aware of the issue. I opened the issue here as the tests are run by PHPUnit and it seems the tests are being run differently when they're inside the VM compared to outside. 

It's obviously possible that it's something that the AWS sdk is doing wrong - but as the tests are run by PHPUnit I thought it appropriate to open it here.

**Comment by Danack** [comment] 2015-02-01 15:13
This was caused by opcache being enabled and not loading comments. This seem likely to be something that catches people out occasionally. Would it be possible to add a warning for this scenario?

```
//If anything is set that requires annotations:
if (ini_get('opcache.enable') == true &&
    ini_get('opcache.save_comments') == false) {
    echo "Cannot run tests. OPCache is enabled and is stripping comments,". 
         "which are required by PHPUnit to provide data for the tests.\n";
}
```

**Comment by whatthejeff** [comment] 2015-02-01 15:20
This has been brought up a couple times before. Here is @sebastianbergmann's previous response: https://github.com/sebastianbergmann/phpunit/issues/1093#issuecomment-34443174. I wouldn't mind seeing some kind of warning.

**Comment by Danack** [comment] 2015-02-01 15:40
My above comment is actually incorrect - it seems that not only must opcache.save_comments be enabled, but opcache.load_comments also needs to be enabled now.

> This has been brought up a couple times before.

*Fool me once, shame on you. Fool me twice, yeah....this is a user experience problem that ought to be addressed.*

**Comment by whatthejeff** [comment] 2015-02-01 19:18
@sebastianbergmann Any opinions on emitting a warning for problematic opcache configurations?

**Comment by sebastianbergmann** [comment] 2015-10-02 04:02
Dear contributor,

let me start by apologizing for not commenting and/or working on the issue you have reported or merging the pull request you have sent sooner.

PHPUnit 5.0 was released today. And today I am closing all open bug reports and pull requests for PHPUnit and its dependencies that I maintain. Please do not interpret the closing of this ticket as an insult or a lack of interest in your problem. I am sorry for any inconvenience this may cause.

If the topic of this ticket is still relevant then please open a new ticket or send a new pull request. If your ticket or pull request is about a defect then please check whether the issue still exists in PHPUnit 4.8 (which will received bug fixes until August 2016). If your ticket or pull request is about a new feature then please port your patch PHPUnit 5.0 before sending a new pull request.

I hope that today's extreme backlog grooming will allow me to respond to bug reports and pull requests in a more timely manner in the future.

Thank you for your understanding,
Sebastian

**Closed by sebastianbergmann** 2015-10-02 04:02 UTC
Labels: rfc
