### ISSUE TITLE
Globally installed phpunit might not work correctly

### ISSUE THREAD

**Issue by neomerx** [sebastianbergmann/phpunit#1605] opened 2015-02-06 15:02 UTC
Globally installed phpunit gives an error of 'Cannot redeclare class' however if installed in vendor folder doesn't give such an error.

More details at https://github.com/laravel/framework/issues/7299

**Comment by BenHicks** [comment] 2015-02-20 09:08
Maybe this has the same cause as https://github.com/sebastianbergmann/phpunit/issues/1600?

**Comment by neomerx** [comment] 2015-02-20 15:56
@BenHicks I don't know what's the cause of the error and I can only say I don't have PEAR installed on my machine.

**Comment by jaceju** [comment] 2015-03-02 07:05
I tried to comment the code in `vendor/nikic/php-parser/lib/bootstrap.php` and it works fine.

```php
// require __DIR__ . '/PhpParser/Autoloader.php';
// PhpParser\Autoloader::register();
```

But it is not a good idea.

**Comment by sebastianbergmann** [comment] 2015-09-18 12:55
Cannot reproduce, closing.

**Closed by sebastianbergmann** 2015-09-18 12:55 UTC
