### ISSUE TITLE
phpunit/phpunit requires abandoned package: sebastian/resource-operations

### ISSUE THREAD

**Issue by bmerigan** [sebastianbergmann/phpunit#4778] opened 2021-09-16 00:08 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.9
| PHP version         | 7.4
| Installation Method | Composer

#### Summary

See a warning message upon running Composer:
`Package sebastian/resource-operations is abandoned, you should avoid using it. No replacement was suggested.`

#### Current behavior

Shows a warning message, due to phpunit package requirments including `sebastian/resource-operations`

```
{  
            "name": "phpunit/phpunit",  
            "version": "9.5.9",  
            "source": {  
                "type": "git",  
                "url": "https://github.com/sebastianbergmann/phpunit.git",  
                "reference": "ea8c2dfb1065eb35a79b3681eee6e6fb0a6f273b"  
            },  
            "dist": {  
                "type": "zip",  
                "url": "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/ea8c2dfb1065eb35a79b3681eee6e6fb0a6f273b",  
                "reference": "ea8c2dfb1065eb35a79b3681eee6e6fb0a6f273b",  
                "shasum": ""  
            },  
            "require": {  
                "doctrine/instantiator": "^1.3.1",  
                "ext-dom": "*",  
                "ext-json": "*",  
                "ext-libxml": "*",  
                "ext-mbstring": "*",  
                "ext-xml": "*",  
                "ext-xmlwriter": "*",  
                "myclabs/deep-copy": "^1.10.1",  
                "phar-io/manifest": "^2.0.3",  
                "phar-io/version": "^3.0.2",  
                "php": ">=7.3",  
                "phpspec/prophecy": "^1.12.1",  
                "phpunit/php-code-coverage": "^9.2.3",  
                "phpunit/php-file-iterator": "^3.0.5",  
                "phpunit/php-invoker": "^3.1.1",  
                "phpunit/php-text-template": "^2.0.3",  
                "phpunit/php-timer": "^5.0.2",  
                "sebastian/cli-parser": "^1.0.1",  
                "sebastian/code-unit": "^1.0.6",  
                "sebastian/comparator": "^4.0.5",  
                "sebastian/diff": "^4.0.3",  
                "sebastian/environment": "^5.1.3",  
                "sebastian/exporter": "^4.0.3",  
                "sebastian/global-state": "^5.0.1",  
                "sebastian/object-enumerator": "^4.0.3",  
                "sebastian/resource-operations": "^3.0.3",  
                "sebastian/type": "^2.3.4",  
                "sebastian/version": "^3.0.2"  
            },  
```

#### How to reproduce

`composer install`

#### Expected behavior

Don't require the abandoned package

#### composer info | sort 
```
brick/math                           0.9.3     Arbitrary-precision arithmetic library  
cache/adapter-common                 1.2.0     Common classes for PSR-6 adapters  
cache/hierarchical-cache             1.1.0     A helper trait and interface to your PSR-6 cache to support hiera...  
cache/tag-interop                    1.0.1     Framework interoperable interfaces for tags  
cache/void-adapter                   1.1.0     A PSR-6 cache implementation using Void. This implementation supp...  
composer/package-versions-deprecated 1.11.99.3 Composer plugin that provides efficient querying for installed pa...  
composer/semver                      3.2.5     Semver library that offers utilities, version constraint parsing ...  
composer/xdebug-handler              2.0.2     Restarts a process without Xdebug.  
contentful/contentful                6.1.0     SDK for the Contentful Content Delivery API  
contentful/core                      3.1.1     Foundation library for Contentful PHP SDKs  
contentful/rich-text                 3.2.0     Utilities for the Contentful Rich Text  
dms/phpunit-arraysubset-asserts      v0.2.0    This package provides ArraySubset and related asserts once deprec...  
doctrine/annotations                 1.13.2    Docblock Annotations Parser  
doctrine/instantiator                1.4.0     A small, lightweight utility to instantiate objects in PHP withou...  
doctrine/lexer                       1.2.1     PHP Doctrine Lexer parser library that can be used in Top-Down, R...  
elastic/apm-agent                    v1.1      Elastic APM PHP Agent  
fig/http-message-util                1.1.5     Utility classes and constants for use with PSR-7 (psr/http-message)  
friendsofphp/php-cs-fixer            v2.19.2   A tool to automatically fix PHP code style  
guzzlehttp/guzzle                    7.3.0     Guzzle is a PHP HTTP client library  
guzzlehttp/promises                  1.4.1     Guzzle promises library  
guzzlehttp/psr7                      1.8.2     PSR-7 message implementation that also provides common utility me...  
http-interop/http-factory-guzzle     1.2.0     An HTTP Factory using Guzzle PSR7  
jean85/pretty-package-versions       1.6.0     A wrapper for ocramius/package-versions to get pretty versions st...  
lastguest/murmurhash                 2.1.1     MurmurHash3 Hash  
lukasoppermann/http-status           2.0.1     A minimal package for working with HTTP statuses.  
monolog/monolog                      2.3.2     Sends your logs to files, sockets, inboxes, databases and various...  
myclabs/deep-copy                    1.10.2    Create deep copies (clones) of your objects  
nikic/fast-route                     v1.3.0    Fast request router for PHP  
nikic/php-parser                     v4.12.0   A PHP parser written in PHP  
phar-io/manifest                     2.0.3     Component for reading phar.io manifest information from a PHP Arc...  
phar-io/version                      3.1.0     Library for handling version information and constraints  
php-cs-fixer/diff                    v1.3.1    sebastian/diff v2 backport support for PHP5.6  
phpdocumentor/reflection-common      2.2.0     Common reflection classes used by phpdocumentor to reflect the co...  
phpdocumentor/reflection-docblock    5.2.2     With this component, a library can provide support for annotation...  
phpdocumentor/type-resolver          1.4.0     A PSR-5 based resolver of Class names, Types and Structural Eleme...  
phpspec/prophecy                     1.13.0    Highly opinionated mocking framework for PHP 5.3+  
phpunit/php-code-coverage            9.2.6     Library that provides collection, processing, and rendering funct...  
phpunit/php-file-iterator            3.0.5     FilterIterator implementation that filters files based on a list ...  
phpunit/php-invoker                  3.1.1     Invoke callables with a timeout  
phpunit/php-text-template            2.0.4     Simple template engine.  
phpunit/php-timer                    5.0.3     Utility class for timing  
phpunit/phpunit                      9.5.9     The PHP Unit Testing framework.  
psr/cache                            1.0.1     Common interface for caching libraries  
psr/container                        1.1.1     Common Container Interface (PHP FIG PSR-11)  
psr/event-dispatcher                 1.0.0     Standard interfaces for event handling.  
psr/http-client                      1.0.1     Common interface for HTTP clients  
psr/http-factory                     1.0.1     Common interfaces for PSR-7 HTTP message factories  
psr/http-message                     1.0.1     Common interface for HTTP messages  
psr/http-server-handler              1.0.1     Common interface for HTTP server-side request handler  
psr/http-server-middleware           1.0.1     Common interface for HTTP server-side middleware  
psr/log                              1.1.4     Common interface for logging libraries  
psr/simple-cache                     1.0.1     Common interfaces for simple caching  
ralouphie/getallheaders              3.0.3     A polyfill for getallheaders.  
ramsey/collection                    1.2.1     A PHP library for representing and manipulating collections.  
ramsey/uuid                          4.2.1     A PHP library for generating and working with universally unique ...  
rregeer/phpunit-coverage-check       0.3.1     Check the code coverage using the clover report of phpunit  
sebastian/cli-parser                 1.0.1     Library for parsing CLI options  
sebastian/code-unit-reverse-lookup   2.0.3     Looks up which function or method a line of code belongs to  
sebastian/code-unit                  1.0.8     Collection of value objects that represent the PHP code units  
sebastian/comparator                 4.0.6     Provides the functionality to compare PHP values for equality  
sebastian/complexity                 2.0.2     Library for calculating the complexity of PHP code units  
sebastian/diff                       4.0.4     Diff implementation  
sebastian/environment                5.1.3     Provides functionality to handle HHVM/PHP environments  
sebastian/exporter                   4.0.3     Provides the functionality to export PHP variables for visualization  
sebastian/global-state               5.0.3     Snapshotting of global state  
sebastian/lines-of-code              1.0.3     Library for counting the lines of code in PHP source code  
sebastian/object-enumerator          4.0.4     Traverses array structures and object graphs to enumerate all ref...  
sebastian/object-reflector           2.0.4     Allows reflection of object attributes, including inherited and n...  
sebastian/recursion-context          4.0.4     Provides functionality to recursively process PHP variables  
sebastian/resource-operations        3.0.3     Provides a list of PHP built-in functions that operate on resources  
sebastian/type                       2.3.4     Collection of value objects that represent the types of the PHP t...  
sebastian/version                    3.0.2     Library that helps with managing the version number of Git-hosted...  
slim/psr7                            1.4       Strict PSR-7 implementation  
slim/slim                            4.8.1     Slim is a PHP micro framework that helps you quickly write simple...  
squizlabs/php_codesniffer            3.6.0     PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detec...  
symfony/cache-contracts              v2.4.0    Generic abstractions related to caching  
symfony/cache                        v5.3.4    Provides an extended PSR-6, PSR-16 (and tags) implementation  
symfony/console                      v5.3.6    Eases the creation of beautiful and testable command line interfaces  
symfony/deprecation-contracts        v2.4.0    A generic function and convention to trigger deprecation notices  
symfony/event-dispatcher-contracts   v2.4.0    Generic abstractions related to dispatching event  
symfony/event-dispatcher             v5.3.4    Provides tools that allow your application components to communic...  
symfony/filesystem                   v5.3.4    Provides basic utilities for the filesystem  
symfony/finder                       v5.3.4    Finds files and directories via an intuitive fluent interface  
symfony/options-resolver             v5.3.4    Provides an improved replacement for the array_replace PHP function  
symfony/polyfill-ctype               v1.23.0   Symfony polyfill for ctype functions  
symfony/polyfill-intl-grapheme       v1.23.1   Symfony polyfill for intl's grapheme_* functions  
symfony/polyfill-intl-normalizer     v1.23.0   Symfony polyfill for intl's Normalizer class and related functions  
symfony/polyfill-mbstring            v1.23.1   Symfony polyfill for the Mbstring extension  
symfony/polyfill-php70               v1.20.0   Symfony polyfill backporting some PHP 7.0+ features to lower PHP ...  
symfony/polyfill-php72               v1.23.0   Symfony polyfill backporting some PHP 7.2+ features to lower PHP ...  
symfony/polyfill-php73               v1.23.0   Symfony polyfill backporting some PHP 7.3+ features to lower PHP ...  
symfony/polyfill-php80               v1.23.1   Symfony polyfill backporting some PHP 8.0+ features to lower PHP ...  
symfony/polyfill-php81               v1.23.0   Symfony polyfill backporting some PHP 8.1+ features to lower PHP ...  
symfony/process                      v5.3.4    Executes commands in sub-processes  
symfony/service-contracts            v2.4.0    Generic abstractions related to writing services  
symfony/stopwatch                    v5.3.4    Provides a way to profile code  
symfony/string                       v5.3.3    Provides an object-oriented API to strings and deals with bytes, ...  
symfony/var-exporter                 v5.3.4    Allows exporting any serializable PHP data structure to plain PHP...  
theseer/tokenizer                    1.2.1     A small library for converting tokenized PHP source code into XML...  
unleash/client                       v1.1.174  
webmozart/assert                     1.10.0    Assertions to validate method input/output with nice error messages.  
```

**Comment by sebastianbergmann** [comment] 2021-09-16 04:59
Duplicate of #4714.

**Closed by sebastianbergmann** 2021-09-16 04:59 UTC
Labels: type/bug
