### ISSUE TITLE
Unable to run unit test case

### ISSUE THREAD

**Issue by vinit2710** [sebastianbergmann/phpunit#2658] opened 2017-04-25 17:47 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.1.1
| PHP version         | 7.1.4
| Installation Method |  PHAR

#### What are you trying to achieve?
I have installed PHPUnit  (PHPUnit 6.1.1 by Sebastian Bergmann and contributors.)  on windows  10 as per https://phpunit.de/manual/current/en/installation.html#installation.phar.windows

I have installed PHP 7.1.4 (cli) (built: Apr 11 2017 19:54:37) ( ZTS MSVC14 (Visual C++ 2015) x64 )

I have created two files Email.php and EmailTest.php in same folder example code as given in https://phpunit.de/getting-started.html

I am running following command
**phpunit EmailTest.php**

However the test is not running.

#### What do you get instead?

```bash
Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, boolean given in phar://C:/bin/phpunit-6.1.1.phar/sebastian-environment/Console.php:115
Stack trace:
#0 phar://C:/bin/phpunit-6.1.1.phar/sebastian-environment/Console.php(115): trim(false)
#1 phar://C:/bin/phpunit-6.1.1.phar/sebastian-environment/Console.php(63): SebastianBergmann\Environment\Console->getNumberOfColumnsWindows()
#2 phar://C:/bin/phpunit-6.1.1.phar/phpunit/TextUI/ResultPrinter.php(173): SebastianBergmann\Environment\Console->getNumberOfColumns()
#3 phar://C:/bin/phpunit-6.1.1.phar/phpunit/TextUI/TestRunner.php(282): PHPUnit\TextUI\ResultPrinter->__construct(NULL, false, 'never', false, 80, false)
#4 phar://C:/bin/phpunit-6.1.1.phar/phpunit/TextUI/Command.php(209): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#5 phar://C:/bin/phpunit-6.1.1.phar/phpunit/TextUI/Command.php(140): PHPUnit\TextUI\Command->run(Array, true)
#6 C:\bin\phpunit-6.1.1.phar(545): PHPUnit\TextUI\Command::main()
#7 {main}
  thr in phar://C:/bin/phpunit-6.1.1.phar/sebastian-environment/Console.php on line 115

**Comment by sebastianbergmann** [comment] 2017-04-25 18:42
Duplicate of #2657.

**Closed by sebastianbergmann** 2017-04-25 18:42 UTC
