### ISSUE TITLE
No stacktrace in 9.5.x?

### ISSUE THREAD

**Issue by temp** [sebastianbergmann/phpunit#4592] opened 2021-01-26 08:44 UTC
Was there a change in the handling of errors in phpunit 9.5.x?
In 9.4.4 I get the following output:
```bash
$ php phpunit-9.4.4.phar
PHPUnit 9.4.4 by Sebastian Bergmann and contributors.

...............................................................  63 / 148 ( 42%)
............................................................... 126 / 148 ( 85%)
...E..................                                          148 / 148 (100%)

Time: 00:00.025, Memory: 26.00 MB

There was 1 error:

1) FncTests\Unit\TailTest::testTail
Exception: foo

/Users/swentz/git/temp/fn/src/functions.php:1100
/Users/swentz/git/temp/fn/tests/Unit/TailTest.php:19

ERRORS!
Tests: 148, Assertions: 202, Errors: 1.
```

While in phpunit 9.5.2 this looks like this:
```bash
$ php phpunit-9.5.2.phar
PHPUnit 9.5.1 by Sebastian Bergmann and contributors.

...............................................................  63 / 148 ( 42%)
............................................................... 126 / 148 ( 85%)
...E..................                                          148 / 148 (100%)

Time: 00:00.022, Memory: 26.00 MB

There was 1 error:

1) FncTests\Unit\TailTest::testTail
Exception: foo

ERRORS!
Tests: 148, Assertions: 202, Errors: 1.
````

The stack trace is missing. I didn't find anything related in the changelogs. 
Is this behaviour expected, or is there something missing on my side?

**Comment by sebastianbergmann** [comment] 2021-01-26 08:48
Duplicate of #4573.

**Closed by sebastianbergmann** 2021-01-26 08:48 UTC
Labels: type/bug
