### ISSUE TITLE
mock ->with($this->callback(callback)) - callback is called once more than expected

### ISSUE THREAD

**Issue by simonbrahan** [sebastianbergmann/phpunit#1601] opened 2015-02-05 15:24 UTC
<?php
    
    class MockedThing
    {
        public function doMockedThing($arg)
        {
            return $arg;
        }
    }
    
    class Thing
    {
        protected $mocked_thing;
    
        public function __construct($mocked_thing)
        {
            $this->mocked_thing = $mocked_thing;
        }
    
        public function doThing($arg)
        {
            $this->mocked_thing->doMockedThing($arg);
        }
    }
    
    class ThingTest extends PHPUnit_Framework_TestCase
    {
        public function testThingHappens()
        {
            $mock = $this->getMockBuilder('MockedThing')
                         ->disableOriginalConstructor()
                         ->getMock();
    
            $validate_param = function ($params) {
                var_dump($params);
                return true;
            };
    
            $mock->expects($this->exactly(2))
                 ->method('doMockedThing')
                 ->with($this->callback($validate_param));
    
            $thing = new Thing($mock);
    
            $thing->doThing('thing 1');
            $thing->doThing('thing 2');
        }
    }

In this code the $validate_param is called three times where I would expect it to be called twice. Output as follows:

    PHPUnit 4.4.5 by Sebastian Bergmann.

    .string(7) "thing 1"
    string(7) "thing 2"
    string(7) "thing 2"

    Time: 16 ms, Memory: 4.00Mb

    OK (1 test, 1 assertion)

Run against PHP 5.3.3.

**Comment by sebastianbergmann** [comment] 2015-02-05 15:58
Is this a duplicate of https://github.com/sebastianbergmann/phpunit-mock-objects/pull/191?

**Comment by simonbrahan** [comment] 2015-02-05 21:38
That fix will only allow one verification to occur. Running my code against that branch produces the following:

    PHPUnit 4.4.5 by Sebastian Bergmann.
    
    .string(7) "thing 1"
    
    
    Time: 15 ms, Memory: 3.00Mb
    
    OK (1 test, 1 assertion)

I would expect an output similar to:

    PHPUnit 4.4.5 by Sebastian Bergmann.
    
    .string(7) "thing 1"
    string(7) "thing 2"
    
    
    Time: 16 ms, Memory: 4.00Mb

OK (1 test, 1 assertion)

**Comment by egeloen** [comment] 2015-04-17 20:48
@simonbrahan Can you give a new try to my branch? I have changed my approach to also deal with your usecase.

**Comment by simonbrahan** [comment] 2015-04-30 18:54
Still doesn't work. I now get the original output again.

**Comment by egeloen** [comment] 2015-04-30 21:40
Hum, strange as I have tested your use case and got the expected output. I need to re-check it...

**Comment by egeloen** [comment] 2015-05-09 07:31
@simonbrahan Are you sure you have well rebased your branch on top of mine? I just re-give it a try and I get the expected output (based on your usecase):

```bash
gelo@Pc-GeLo:~/Workspace/PHPUnit/phpunit-mock-objects$ ./vendor/bin/phpunit tests/ThingTest.php 
PHPUnit 4.6.4 by Sebastian Bergmann and contributors.

Configuration read from /home/gelo/Workspace/PHPUnit/phpunit-mock-objects/phpunit.xml.dist

.string(7) "thing 1"
string(7) "thing 2"


Time: 211 ms, Memory: 13.00Mb

OK (1 test, 1 assertion)

Generating code coverage report in HTML format ... done
```

**Comment by sebastianbergmann** [comment] 2015-06-21 08:13
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md) have been reported on the [phpunit-mock-objects](https://github.com/sebastianbergmann/phpunit-mock-objects) project instead.

**Closed by sebastianbergmann** 2015-06-21 08:13 UTC
