### ISSUE TITLE
fake tests success with clover report in TravisCI

### ISSUE THREAD

**Issue by yurii-github** [sebastianbergmann/phpunit#1759] opened 2015-06-22 18:00 UTC
i see successful report even when tests are failing on such run
phpunit --coverage-clover {some-path}
my live example: https://travis-ci.org/yurii-github/yii2-mylib/jobs/67876280

as i understand, TravisCI checks exit code, so PHPUnit is always on success as clover never fails.
is there some config option? i have set throw exceptions on everything and stop on first error.

also, it is strange that PHPUnit always finishes clover report even when tests are failing. Personally i don't see any sense in this as this report won't have real cover.

regards

**Comment by sebastianbergmann** [comment] 2015-06-22 18:03
Duplicate of #1638.

**Closed by sebastianbergmann** 2015-06-22 18:03 UTC

**Comment by yurii-github** [comment] 2015-06-22 18:13
thanks for fast closing, but there's no solution in duplicates.

is there option to not run clover if tests are failing?

**Comment by yurii-github** [comment] 2015-06-22 18:39
i found my mistake. sorry
