### ISSUE TITLE
`expectDeprecation` stopped working since phpunit 9.5.10

### ISSUE THREAD

**Issue by mvorisek** [sebastianbergmann/phpunit#4788] opened 2021-09-29 13:15 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.10
| PHP version         | any
| Installation Method | Composer

#### Summary

`expectDeprecation` does not work

#### Current behavior

Deprecated warning is not caught by `expectDeprecation`

#### How to reproduce

worked until https://github.com/atk4/core/runs/3706924981?check_suite_focus=true

broken since https://github.com/atk4/core/runs/3707321163?check_suite_focus=true (the only dep. chance is phpunit from 9.5.9 to 9.5.10)

code https://github.com/atk4/core

**Comment by sebastianbergmann** [comment] 2021-09-29 13:18
Duplicate of #4786.

**Closed by sebastianbergmann** 2021-09-29 13:18 UTC
Labels: type/bug
