### ISSUE TITLE
Test without @covers annotation is only marked as risky when forceCoversAnnotation=true and beStrictAboutCoversAnnotation=true is set

### ISSUE THREAD

**Issue by nickel715** [sebastianbergmann/phpunit#3376] opened 2018-10-31 12:35 UTC
In our project the `forceCoversAnnotation` option is enabled.
This option causes tests without covers annotations to cover nothing.
So it would be really helpful to get a warning about these tests without covers annotations.
In `CodeCoverage` there is a option `checkForMissingCoversAnnotation` which is enabled if `strictCoverage` is enabled, unfortunately this option also requires the uses annotations and we don't want to use them as they are to strict.

So as a solution I've two suggestions (I provide a PR for both):

> Introduce a new option to only check missing covers annotations #3374 

or

> Automatically check for missing covers annotations if `forceCoversAnnotation` is enabled #3375

For me the second option is my favorite because is see no benefit of having tests without covering anything.

What do you think about this feature? Which solution makes more sense in your opinion.

**Comment by sebastianbergmann** [comment] 2018-10-31 12:39
I do not understand

> So it would be really helpful to get a warning about these tests without covers annotations.

as PHPUnit marks any test without a `@covers` annotation as risky when `forceCoversAnnotation="true"` is set.

**Comment by nickel715** [comment] 2018-10-31 12:55
Then it seams to be a bug. I tested it in an isolated environment and i got no warning from phpunit: https://github.com/nickel715/phpunit-check-missing-covers-test

**Comment by sebastianbergmann** [comment] 2018-10-31 13:14
Yes, this seems to be a bug.

A test without a `@covers` annotation is only marked as risky when `forceCoversAnnotation=true` and `beStrictAboutCoversAnnotation=true` is set. It should also be marked as risky when only `forceCoversAnnotation=true` is set.

**Comment by nickel715** [comment] 2018-10-31 13:20
So then #3375 should fix this bug?

**Comment by nickel715** [comment] 2018-10-31 13:53
I created a new branch as the old one was based on master. 
The new branch is based on the latest release and contains fix for broken build

**Comment by sebastianbergmann** [comment] 2018-10-31 14:39
I did some digging and found https://github.com/sebastianbergmann/phpunit/commit/ac0528f7b12668ee6b744a27893da4ab7b0ffd02 and https://github.com/sebastianbergmann/php-code-coverage/commit/9c3582b20a916a5599ede39dea4b1248d1ad46d1.

I do not remember my reasoning from 2.5 years ago, but it appears that the current behaviour is intentional. So it's not a bug. Changing this would be a breaking change which I am not willing to do at this point in time. We might revisit this in the future.

It's also not really an issue, as using both `forceCoversAnnotation=true` and `beStrictAboutCoversAnnotation=true` is considered best practice.

**Closed by sebastianbergmann** 2018-10-31 14:39 UTC
Labels: bug

**Comment by nickel715** [comment] 2018-10-31 15:33
thanks for digging! 
So as this behavior is intended I will come back to my feature request of having a additional option for only checking missing covers.

Not everyone wants this severity of strictness, like in our case we want to force covers annotations but don't want so mess with the uses annotations. 

What's the disadvantage of adding this additional argument?
