### ISSUE TITLE
PHPUnit 10 crashes on Fatal error during test

### ISSUE THREAD

**Issue by MoonE** [sebastianbergmann/phpunit#5255] opened 2023-02-25 01:55 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.11
| PHP version         | 8.1.12
| Installation Method | Composer

#### Summary

PHPUnit crashes when it tries to log a fatal error during a test case.

#### Current behavior

vendor/phpunit/phpunit/src/Logging/JUnit/JunitXmlLogger.php:314
JunitXmlLogger.::handleFault:
        `$this->currentTestCase` is null and `appendChild` fails

#### How to reproduce

Caused by this error:
> PHP Fatal error: Class PhpMyAdmin\Gis\GisLineString contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PhpMyAdmin\Gis\GisGeometry::getCoordinateParams) in [...]/phpmyadmin/libraries/classes/Gis/GisLineString.php on line 23

Which is an error in my php file, but PHPUnit fails to log it.

#### Expected behavior

PHPUnit will finish all tests and print the error message for the failed test.

**Comment by MoonE** [comment] 2023-02-25 02:26
I see a fixed has been committed with #5251 but I still get this error with the latest version installed from git.
```
$ composer phpunit
@php phpunit --color=always
PHPUnit 10.0.11-27-gd9fee5ab9 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.12
Configuration:[...]/phpmyadmin/phpunit.xml.dist
Random Seed:   1677291435

EEEEEEEE...................................................   59 / 3272 (  1%)
...........................................................  118 / 3272 (  3%)
...........................................................  177 / 3272 (  5%)
...........................................................  236 / 3272 (  7%)
.D.........................................................  295 / 3272 (  9%)
.........................................................E

An error occurred inside PHPUnit.

Message:  Call to a member function appendChild() on null
Location: [...]/phpunit/src/TextUI/TestRunner.php:68

#0 [...]/phpunit/src/TextUI/Application.php(142): PHPUnit\TextUI\TestRunner->run()
#1 [...]/phpunit/phpunit(90): PHPUnit\TextUI\Application->run()
#2 {main}
```

**Comment by sebastianbergmann** [comment] 2023-02-25 05:22
Duplicate of #5251.

**Closed by sebastianbergmann** 2023-02-25 05:22 UTC
Labels: type/bug, version/10

**Comment by MoonE** [comment] 2023-02-25 05:39
I still get this error. even with the latest version from git. See my above comment 
> PHPUnit 10.0.11-27-gd9fee5ab9

Please reopen the issue.
