### ISSUE TITLE
PHPUnit 10.0 significantly slower than PHPUnit 9.6

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/phpunit#5184] opened 2023-02-08 14:27 UTC
Hi, updating my biggest project from `9.6` to `10.0` shows execution time **doubling** at best.
Here are some numbers:

| PHPUnit | Time | Diff | Memory |
| - | - | - | - |
| `9.6` 1st run | 02:29.786 | Δ | 1.13 GB |
| `9.6` 2nd run | 02:29.785 | Δ | 1.12 GB |
| `9.6` 3rd run | 02:28.535 | Δ | 1.13 GB |
| `10.0` 1st run | 06:09.392 | +148% | 1.18 GB |
| `10.0` 2nd run | 06:19.358 | +154% | 1.17 GB |
| `10.0` 3rd run | 06:10.374 | +148% | 1.17 GB |

Some context:

* No code change was needed, only `composer.json` has been edited
* No Listener/Extension used
* `--no-coverage` flag in place
* `--no-logging` flag in place
* `--do-not-cache-result` flag in place

I'd like to help you idenfity the issue, but I need some clue: how could I effectively compare PHPUnit's internals from `9.6` to `10.0`?

**Comment by sebastianbergmann** [comment] 2023-02-08 14:31
The only sensible explanation that comes to mind would be the event system. Maybe along the lines of what was reported in #5183.

**Comment by sebastianbergmann** [comment] 2023-02-08 14:34
I do not think that it makes any sense to "compare PHPUnit's internals from 9.6 to 10.0". Instead, somebody should use a profiler and look for code paths in PHPUnit 10 that can be optimized.

**Comment by Slamdunk** [comment] 2023-02-08 14:41
Whoa #5183 is right! Execution time on 10.0 dropped even lower than 9.6:

`Time: 02:00.907, Memory: 1.14 GB`

After applying just this patch:

```diff
--- a/src/Event/Emitter/DispatchingEmitter.php
+++ b/src/Event/Emitter/DispatchingEmitter.php
@@ -403,7 +403,7 @@ public function testAssertionSucceeded(mixed $value, Constraint\Constraint $cons
         $this->dispatcher->dispatch(
             new Test\AssertionSucceeded(
                 $this->telemetryInfo(),
-                (new Exporter)->export($value),
+                'null',
                 $constraint->toString(),
                 $constraint->count(),
                 $message,
```

**Comment by sebastianbergmann** [comment] 2023-02-08 14:41
To assess whether this might be related to #5183, can you please try with this change:
```diff
diff --git a/src/Event/Emitter/DispatchingEmitter.php b/src/Event/Emitter/DispatchingEmitter.php
index 2da86da97..b67dd2b7e 100644
--- a/src/Event/Emitter/DispatchingEmitter.php
+++ b/src/Event/Emitter/DispatchingEmitter.php
@@ -403,7 +403,7 @@ public function testAssertionSucceeded(mixed $value, Constraint\Constraint $cons
         $this->dispatcher->dispatch(
             new Test\AssertionSucceeded(
                 $this->telemetryInfo(),
-                (new Exporter)->export($value),
+                '',
                 $constraint->toString(),
                 $constraint->count(),
                 $message,
@@ -420,7 +420,7 @@ public function testAssertionFailed(mixed $value, Constraint\Constraint $constra
         $this->dispatcher->dispatch(
             new Test\AssertionFailed(
                 $this->telemetryInfo(),
-                (new Exporter)->export($value),
+                '',
                 $constraint->toString(),
                 $constraint->count(),
                 $message,
```

This causes the `Test\AssertionSucceeded` and `Test\AssertionFailed` events to be emitted without exported values.

**Comment by sebastianbergmann** [comment] 2023-02-08 14:42
Wow! We both posted the same suggestion at about the same time.

**Comment by sebastianbergmann** [comment] 2023-02-08 14:42
Duplicate of #5183.

**Closed by sebastianbergmann** 2023-02-08 14:42 UTC
Labels: feature/test-runner, type/performance, version/10
