### ISSUE TITLE
Mocking a final method from a base class on a class extending it fails silently

### ISSUE THREAD

**Issue by pzaj2** [sebastianbergmann/phpunit#3314] opened 2018-09-27 07:28 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.3.5
| PHP version         | 7.2.9
| Installation Method | Composer

Simply put, mocking a class extending `\Exception` I was wondering why `getMessage` returns an empty string despite being mocked. It happens to be a public final method of `\Exception`. While I haven't checked, I'd risk saying that this will happen for other classes with final methods being extended.

Expected behaviour:
Issue / display a warning saying this method cannot be mocked / stubbed.

Actual behaviour:
The method is not mocked, it works as it would normally (in this case returning an empty string).

**Comment by sebastianbergmann** [comment] 2018-09-27 19:32
Duplicate of #3127.

**Closed by sebastianbergmann** 2018-09-27 19:32 UTC
