### ISSUE TITLE
Shows incorrect failed message with closed Generator

### ISSUE THREAD

**Issue by ssi-anik** [sebastianbergmann/phpunit#5079] opened 2022-10-13 01:47 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.25
| PHP version         | 8.1.11
| Installation Method | Composer

#### Summary

When trying `assertCount` with a generator, a mismatch between the expected and generator count will show an invalid message. The reason is that the Generator is closed during the evaluation, and cannot get the count when generating the message.

#### Current behavior

`Failed asserting that actual size 0 matches expected size EXPECTED_VALUE`

#### How to reproduce

```php
public function testGenerator () {
    $items = (function () {
        foreach (range(1, 10) as $item) {
            yield $item;
        }
    })();

    $this->assertCount(11, $items);
}
```

#### Expected behavior

`Failed asserting that actual size ACTUAL_SIZE matches expected size EXPECTED_VALUE`

**Comment by sebastianbergmann** [comment] 2022-10-13 04:54
Duplicate of #4271.

**Closed by sebastianbergmann** 2022-10-13 04:54 UTC
Labels: type/bug
