### ISSUE TITLE
unrecognized option --run

### ISSUE THREAD

**Issue by SlavomirHutka** [sebastianbergmann/phpunit#2024] opened 2016-01-04 16:21 UTC
I updated phpunit from version 4.4 to version 5.1.3.
php phpunit.phar --version
PHPUnit 4.4.5 by Sebastian Bergmann.
php phpunit.phar --version
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.

I have:
* PHP Version 5.6.16-1~dotdeb+7.1
* PHPUnit 5.1.3
* Netbeans 8.0.2

I execute test by command line and by Nebeans.

By cmd ( command line):
Run command: 
php vendor/phpunit/phpunit.phar --bootstrap test/bootstrapTests.php -c test/phpunit.xml
In both version is all right.

By Netbeans:
Netbeans runs: 
"/usr/bin/php" "/home/hutka/NetBeansProjects/www/betsys/vendor/phpunit/phpunit.phar" "--colors" "--log-junit" "/tmp/nb-phpunit-log.xml" "--bootstrap" "/home/hutka/NetBeansProjects/www/betsys/test/bootstrapTests.php" "--configuration" "/home/hutka/NetBeansProjects/www/betsys/test/phpunit.xml" "/home/hutka/netbeans-8.0.2/php/phpunit/NetBeansSuite.php" "--run=/home/hutka/NetBeansProjects/www/betsys/test"
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.
 
unrecognized option --run
Done.

In version 4.4 is ok. In version 5.1.3 tests not run and finished with **"unrecognized option --run"**

I read changlog in phpunit v4.4 and v5.1.3 and didn't find information about deprecated option --run

Could you help me?

**Comment by sebastianbergmann** [comment] 2016-01-04 17:06
Duplicate of #1818 / #1967.

**Closed by sebastianbergmann** 2016-01-04 17:06 UTC

**Comment by SlavomirHutka** [comment] 2016-01-04 17:58
Thanks you. I will report this with the vendor of your IDE.

**Comment by jefersonbrito** [comment] 2018-01-22 13:14
Hello!
There is any soluction for this problem ?
