### ISSUE TITLE
Serialization of 'Closure' is not allowed and processIsolation="true" when using composer 2.5

### ISSUE THREAD

**Issue by mariano-dagostino** [sebastianbergmann/phpunit#5117] opened 2022-12-21 20:49 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.26
| PHP version         | 8.1
| Installation Method | Composer

#### Summary

The last release of composer 2.5, [includes](https://github.com/composer/composer/pull/11015) a closure in the `vendor/composer/ClassLoader.php` when running composer install.

When running test using the option `processIsolation="true"` in phpunit.xml.dist this leads to the following error:

`Serialization of 'Closure' is not allowed`.

Some other notes:

- This is not the case when running composer 2.4.* same test run fine.  
- Composer 2.5 and `processIsolation="false"` also works. The problem seems to be the combination of the Closure generated by composer 2.5 and the use of processIsolation.

#### How to reproduce

- Use composer 2.5.
- Configure phpunit.dist.xml to use `processIsolation="true"``
- Run the tests.

#### Expected behavior

Test should run, or at least warn to not use process isolation when running composer 2.5

**Comment by sebastianbergmann** [comment] 2022-12-22 06:19
I cannot reproduce this:

```
$ tree
.
├── composer.json
├── phpunit.xml
├── src
└── tests
    └── ExampleTest.php

2 directories, 3 files
```
#### `composer.json`
```json
{
    "require-dev": {
        "phpunit/phpunit": "^9.5"
    }
}
```
#### `phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.5/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         cacheResultFile=".phpunit.cache/test-results"
         executionOrder="depends,defects"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         convertDeprecationsToExceptions="true"
         failOnRisky="true"
         failOnWarning="true"
         processIsolation="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <coverage cacheDirectory=".phpunit.cache/code-coverage"
              processUncoveredFiles="true">
        <include>
            <directory suffix=".php">src</directory>
        </include>
    </coverage>
</phpunit>
```
#### `tests/ExampleTest.php`
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class ExampleTest extends TestCase
{
    public function testOne(): void
    {
        $this->assertTrue(true);
    }
}
```
```
$ composer --version       
Composer version 2.5.0 2022-12-20 10:44:08
```
```
$ composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 28 installs, 0 updates, 0 removals
  - Locking doctrine/instantiator (1.4.1)
  - Locking myclabs/deep-copy (1.11.0)
  - Locking nikic/php-parser (v4.15.2)
  - Locking phar-io/manifest (2.0.3)
  - Locking phar-io/version (3.2.1)
  - Locking phpunit/php-code-coverage (9.2.22)
  - Locking phpunit/php-file-iterator (3.0.6)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (5.0.3)
  - Locking phpunit/phpunit (9.5.27)
  - Locking sebastian/cli-parser (1.0.1)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.8)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.4)
  - Locking sebastian/exporter (4.0.5)
  - Locking sebastian/global-state (5.0.5)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (3.2.0)
  - Locking sebastian/version (3.0.2)
  - Locking theseer/tokenizer (1.2.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 28 installs, 0 updates, 0 removals
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (3.2.0): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.5): Extracting archive
  - Installing sebastian/exporter (4.0.5): Extracting archive
  - Installing sebastian/environment (5.1.4): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.8): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing nikic/php-parser (v4.15.2): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.22): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.11.0): Extracting archive
  - Installing doctrine/instantiator (1.4.1): Extracting archive
  - Installing phpunit/phpunit (9.5.27): Extracting archive
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
25 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
```
$ ./vendor/bin/phpunit
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.0
Configuration: /tmp/example/phpunit.xml

.                                                                   1 / 1 (100%)

Time: 00:00.054, Memory: 6.00 MB

OK (1 test, 1 assertion)
```

**Comment by sebastianbergmann** [comment] 2022-12-22 06:19
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment] 2022-12-22 06:20
@Seldaek Is there anything in Composer 2.5 that PHPUnit needs to deal with? Thanks!

**Comment by Seldaek** [comment] 2022-12-22 08:49
We may need to make the ClassLoader serializable (and delete/revive the closure on serialize/unserialize). I'll investigate this later. I suspect there is nothing you can do here but it's just my current gut feeling.

**Comment by sebastianbergmann** [comment] 2022-12-22 08:49
Okay, thanks. My gut feels the same ;)

**Comment by Seldaek** [comment] 2022-12-22 10:10
Hopefully addressed by https://github.com/composer/composer/pull/11237

**Comment by mariano-dagostino** [comment] 2022-12-22 13:28
Confirming https://github.com/composer/composer/pull/11237 fixes the problem. Thanks all!

**Closed** 2022-12-22 13:47 UTC
Labels: type/bug, status/waiting-for-feedback, installation/composer

**Comment by Seldaek** [comment] 2022-12-22 15:00
If anyone lands here via google, make sure you update to Composer 2.5.1 and then `composer dump-autoload` to ensure the new ClassLoader is present in your vendor dir.
