### ISSUE TITLE
Error in phpunit

### ISSUE THREAD

**Issue by afoysal** [sebastianbergmann/phpunit#2471] opened 2017-02-05 11:26 UTC
PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in D:\php7\htdocs\learn\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1046
Stack trace:
#0 D:\php7\htdocs\learn\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(167): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 D:\php7\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 D:\php7\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 D:\php7\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in D:\php7\htdocs\learn\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1046

Fatal error: Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in D:\php7\htdocs\learn\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1046

Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in D:\php7\htdocs\learn\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1046

Call Stack:
    0.0003     345344   1. {main}() D:\php7\php\phpunit:0
    0.6015     539984   2. PHPUnit_TextUI_Command::main() D:\php7\php\phpunit:46
    0.6015     542288   3. PHPUnit_TextUI_Command->run() D:\php7\php\pear\PHPUnit\TextUI\Command.php:129
    1.5609    2122272   4. PHPUnit_TextUI_TestRunner->doRun() D:\php7\php\pear\PHPUnit\TextUI\Command.php:176
    1.5609    2122296   5. PHPUnit_TextUI_TestRunner->handleConfiguration() D:\php7\htdocs\learn\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:167

**Comment by sebastianbergmann** [comment] 2017-02-05 11:28
Duplicate of #2432.

**Closed by sebastianbergmann** 2017-02-05 11:28 UTC
