### ISSUE TITLE
expectExceptionMessage does not fail when testing wierd value

### ISSUE THREAD

**Issue by marcelloh** [sebastianbergmann/phpunit#3259] opened 2018-08-20 12:27 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.3.1
| PHP version         | 7.2.9
| Installation Method | Composer

```
$this->expectException(AUException::class);
$this->expectExceptionMessage('ha');
$oModel->nonexistingfield = 'value';
```
The exception emssage is different, so I expect the I expect the $this->expectExceptionMessage('ha');
to fail, but it doesn't.

The class throws an AUException with message
BaseModel->__set: Country has no field 'nonexistingfield'

The code goes to this part
```
            if ($this->expectedExceptionMessage !== null) {
                $this->assertThat(
                    $exception,
                    new ExceptionMessage(
                        $this->expectedExceptionMessage
                    )
                );
            }
```
that will bring the program to 
```
public static function assertThat($value, Constraint $constraint, string $message = ''): void
    {
        self::$count += \count($constraint);

        $constraint->evaluate($value, $message);
    }
```
that will go to:
```
public function evaluate($other, $description = '', $returnResult = false)
    {
        $success = false;

        if ($this->matches($other)) {
            $success = true;
        }

        if ($returnResult) {
            return $success;
        }

        if (!$success) {
            $this->fail($other, $description);
        }
    }
```
and it says it is a match. But it matches 2 objects instead of 2 strings.
Which is where is probably goes wrong.

other: Prg\Common\Exceptions\AUException
this: PHPUnit\Framework\Constraint\ExceptionMessage
I found out with digging deeper, the mathces does not match but does a contains kind of check... Nogw that I know, I think, that is even better, but perhaps a good idea to document this?

**Comment by sebastianbergmann** [comment] 2018-08-20 12:28
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by marcelloh** [comment] 2018-08-20 13:29
oh, it's not the same as a contains, since I can do multiple contains
but only one expectExceptionMessage

Country->notExistingMethod() cannot be called with arguments

So I can't do:
$this->expectExceptionMessage("Country->notExistingMethod()");
$this->expectExceptionMessage("cannot be called with arguments");

**Comment by sebastianbergmann** [comment] 2018-08-21 08:52
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by vsouz4** [comment] 2018-09-01 08:59
@marcelloh this is documented:

> The expected message can be a substring of the exception Message. This can be useful to only assert that a certain name or parameter that was passed in shows up in the exception and not fixate the whole exception message in the test.

here: https://phpunit.de/manual/6.5/en/appendixes.annotations.html#appendixes.annotations.expectedExceptionMessage

So this is not an issue/bug nor lack of documentation. Thus, there's no reproducing example :). What you seem to be suggesting though is a non existing feature, where you can run several `expectedExceptionMessage` and all of them will be checked in the same test case (which imho I find very unnecessary, since either you place the entire message or the important part only).

**Closed** 2018-09-05 06:46 UTC
Labels: waiting-for-reproducing-example
