### ISSUE TITLE
Problem with `WithoutErrorHandler` and `DataProvider` attribute on same test

### ISSUE THREAD

**Issue by jbcr** [sebastianbergmann/phpunit#5936] opened 2024-09-03 08:50 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.30
| PHP version         | 8.2.22
| Installation Method | Composer

#### Summary

Conflict when using `WithoutErrorHandler` and `DataProvider` attribute on same test function

#### Current behavior

The attribute `WithoutErrorHandler` is ignored.

#### How to reproduce

```php
<?php

class ClassATest extends TestCase
{
    #[WithoutErrorHandler]
    #[DataProvider('wrongRegex')]
    public function testRegexWrong(string $regex): void
    {
        @preg_match('/^'.$regex.'$/', 'message');
        $this->assertNotNull(error_get_last());
    }

    public function wrongRegex(): array
    {
        return [
            ['[?-9'],
            ['(4'],
        ];
    }
}
```

#### Expected behavior

Test must be executed twice (one per data provider array row) and success because PhpUnit error hander has been disabled.

**Comment by sebastianbergmann** [comment] 2024-09-03 09:03
I cannot reproduce this:

#### `Issue5936Test.php`
```php
<?php declare(strict_types=1);
namespace PHPUnit\TestFixture\Issue5936;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\WithoutErrorHandler;
use PHPUnit\Framework\TestCase;

final class Issue5936Test extends TestCase
{
    #[WithoutErrorHandler]
    #[DataProvider('wrongRegex')]
    public function testRegexWrong(string $regex): void
    {
        @preg_match('/^'.$regex.'$/', 'message');

        $this->assertNotNull(error_get_last());
    }

    public function wrongRegex(): array
    {
        return [
            ['[?-9'],
            ['(4'],
        ];
    }
}
```
```
$ ./phpunit --no-configuration Issue5936Test.php
PHPUnit 10.5.30-31-geae5514716 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.11

D.                                                                  2 / 2 (100%)

Time: 00:00.014, Memory: 10.00 MB

1 test triggered 1 PHPUnit deprecation:

1) PHPUnit\TestFixture\Issue5936\Issue5936Test::testRegexWrong
Data Provider method PHPUnit\TestFixture\Issue5936\Issue5936Test::wrongRegex() is not static

/usr/local/src/phpunit/Issue5936Test.php:12

OK, but there were issues!
Tests: 2, Assertions: 2, Deprecations: 1.
```
When I declare the data provider method to be `static` then I do not get the PHPUnit deprecation:
```
./phpunit --no-configuration Issue5936Test.php
PHPUnit 10.5.30-31-geae5514716 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.11

..                                                                  2 / 2 (100%)

Time: 00:00.013, Memory: 10.00 MB

OK (2 tests, 2 assertions)
```
As you can see, two tests (one for each set of input provided by the data provider method) are run and both tests are successful.

**Comment by jbcr** [comment] 2024-09-03 09:24
The problem can from the configuration?

THis is my configuration:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.5/phpunit.xsd" 
         backupGlobals="false" colors="true" 
         bootstrap="tests/bootstrap.php" 
         executionOrder="random" 
         resolveDependencies="true" 
         beStrictAboutOutputDuringTests="true" 
         cacheDirectory=".phpunit.cache" 
         requireCoverageMetadata="false" 
         beStrictAboutCoverageMetadata="false">
  <php>
    <ini name="error_reporting" value="-1"/>
    <server name="APP_ENV" value="test" force="true"/>
    <server name="SHELL_VERBOSITY" value="-1"/>
    <server name="SYMFONY_PHPUNIT_REMOVE" value=""/>
    <server name="SYMFONY_PHPUNIT_VERSION" value="10.5"/>
    <env name="SYMFONY_DEPRECATIONS_HELPER" value="disabled"/>
  </php>
  <testsuites>
    <testsuite name="default">
      <directory suffix="Test.php">tests/Unit</directory>
    </testsuite>
  </testsuites>
  <source>
    <include>
      <directory suffix=".php">src</directory>
    </include>
  </source>
</phpunit>
```

**Comment by jbcr** [comment] 2024-09-03 10:14
No, I execute test with `vendor/bin/phpunit` command.

The `vendor/bin/simple-phpunit` return this error (out of scope):

```
Warning: Class "Symfony\Bridge\PhpUnit\Legacy\CommandForV9" not found in /var/www/cadeaux-com/vendor/symfony/phpunit-bridge/TextUI/Command.php on line 17

Fatal error: Uncaught Error: Class "PHPUnit\TextUI\Command" not found in /var/www/cadeaux-com/vendor/symfony/phpunit-bridge/Legacy/CommandForV9.php:25
```

**Comment by sebastianbergmann** [comment] 2024-09-04 05:08
This could be caused by code in your `tests/bootstrap.php` file and/or by your test code and/or your tested code.

I close this issue now as PHPUnit works correctly and I cannot debug your environment and/or test suite, sorry.

**Closed by sebastianbergmann** 2024-09-04 05:08 UTC
Labels: type/bug, feature/test-runner, feature/data-provider

**Comment by jbcr** [comment] 2024-09-04 06:49
I have disable the bootstrap file without change the result.

It work if I add the `#[RunInSeparateProcess]` attribute on test. Why ?
