### ISSUE TITLE
Mocking a @method won't work

### ISSUE THREAD

**Issue by ctindogaru** [sebastianbergmann/phpunit#3166] opened 2018-06-13 13:02 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.3
| PHP version         | 7.2.2
| Installation Method | PHAR

Hello, mocking a php method which is defined with @method annotation won't work. It leads to the following warning:
"Trying to configure method "method_name" which cannot be configured because it does not exist, has not been specified, is final, or is static"

You can read more about the annotation here: https://docs.phpdoc.org/references/phpdoc/tags/method.html.

**Comment by sebastianbergmann** [comment] 2018-06-13 13:56
Duplicate of #3121.

**Closed by sebastianbergmann** 2018-06-13 13:56 UTC
