### ISSUE TITLE
Asserting two DateTime objects fails with strange error

### ISSUE THREAD

**Issue by murnieza** [sebastianbergmann/phpunit#2456] opened 2017-01-30 17:25 UTC
While asserting two DateTime objects I ran into the problem when test fails, but actual and expected results are not shown. Instead of that single line is displayed. Objects represent the same timestamp, so test should not be failing.

This is my test:
```
public function testAssertDates()
{
    $dateTime = new \DateTime('2017-01-31 09:30', new \DateTimeZone('UTC'));
    $dateTime->setTimezone(new \DateTimeZone('CET'));

    $this->assertEquals(new \DateTime('2017-01-31 10:30', new \DateTimeZone('CET')), $dateTime);
}
```
This is the result I am getting:
```
$ vendor/bin/phpunit --filter testAssertDates
PHPUnit 5.7.9 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 802 ms, Memory: 14.00MB

There was 1 failure:

1) Tests\AppBundle\Functional\EventRequestForm::testAssertDates
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual
@@ @@
 2017-01-31T10:30:00.000000+0100
```

PHP version:
```
$ php -v
PHP 7.0.12-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0-dev, Copyright (c) 2002-2016, by Derick Rethans
```

Let me know if I any other details are needed.

**Comment by sebastianbergmann** [comment] 2017-02-04 06:16
The code that performs the comparison is [here](https://github.com/sebastianbergmann/comparator/blob/1.2/src/DateTimeComparator.php#L43).

I don't know what is going wrong here, maybe @derickr can help. Derick?

**Comment by JoolsMcFly** [comment] 2017-02-06 14:11
Hi,

issue seems to be with PHP itself. Here's how to repro in pure PHP by comparing dates the way DateTimeComparator::assertEquals does:

```
$start = new \DateTime('2017-01-31 09:30', new \DateTimeZone('UTC'));
$start->setTimezone(new \DateTimeZone('CET'));
$end = clone $start;
$delta = new \DateInterval(sprintf('PT%sS', abs(0)));
var_dump($start > $end->add($delta));   // outputs TRUE even though we're adding 0 seconds
```

If you run the same test but with `$end->sub($delta)` then it outputs `false` (expected).

Now, if you set the timezone directly in the call to DateTime then everything works as expected:
```
$start = new \DateTime('2017-01-31 09:30 UTC');
$end = clone $start;
$delta = new \DateInterval(sprintf('PT%sS', abs(0)));
var_dump($start > $end->add($delta)); // outputs FALSE
```

One way to fix it would be to consider two dates equals if the difference in seconds between the two is 0
```
    public function assertEquals($expected, $actual, $delta = 0.0, $canonicalize = false, $ignoreCase = false, array &$processed = array())
    {
        $delta = new \DateInterval(sprintf('PT%sS', abs($delta)));

        $expectedCloned = clone $expected;

        if ($actual->diff($expectedCloned->add($delta))->s == 0) {
            throw new ComparisonFailure(
                $expected,
                $actual,
                $this->dateTimeToString($expected),
                $this->dateTimeToString($actual),
                false,
                'Failed asserting that two DateTime objects are equal.'
            );
        }
    }
```

I can make a PR if you prefer.

**Comment by derickr** [comment] 2017-02-06 16:42
Looks like a PHP bug. Please file a ticket with your reproducible case at https://bugs.php.net.

**Comment by sebastianbergmann** [comment] 2017-02-06 16:51
Thanks, @derickr. Closing this as it is a bug in PHP.

**Closed by sebastianbergmann** 2017-02-06 16:51 UTC
Labels: 5.7, 6.0, bug
