### ISSUE TITLE
--report-useless-tests and mock objects

### ISSUE THREAD

**Issue by benjamin-rtblw** [sebastianbergmann/phpunit#2126] opened 2016-03-31 12:56 UTC
Hi,

I'm using the mock system of PHPUnit, not Prophecy and I have the following test :

```
<?php
public function testSample()
{
    $mock = $this->getMock('MyClass');
    $mock->expects($this->once())
        ->method('method')
        ->with('param1', 'param2')
        ->willReturn('return');

    $object = new Object();
    $object->setSample($mock);
    $object->run();
}
?>
```

When I run my test with the --report-useless-tests option, PHPUnit considers that test as risky and thinks there is no assertion. But $this->once() and ->with() are both assertions. So why is my test considered as risky ?

Regards,
Ben

**Comment by sebastianbergmann** [comment] 2016-03-31 13:18
I cannot reproduce this:
```php
<?php
class Dependency
{
    public function doSomething($a, $b)
    {
    }
}

class Example
{
    public function run(Dependency $dep)
    {
        $dep->doSomething('a', 'b');
    }
}

class Test extends PHPUnit_Framework_TestCase
{
    public function testOne()
    {
        $mock = $this->getMock(Dependency::class);

        $mock->expects($this->once())
             ->method('doSomething')
             ->with('a', 'b')
             ->willReturn('result');

        $object = new Example;
        $object->run($mock);
    }
}
```
```
$ phpunit --report-useless-tests Test
PHPUnit 5.2.12 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 28 ms, Memory: 4.00Mb

OK (1 test, 1 assertion)
```

**Comment by sebastianbergmann** [comment] 2016-04-08 08:42
No feedback, closing.

**Closed by sebastianbergmann** 2016-04-08 08:42 UTC
