### ISSUE TITLE
DataProviders get executed beforehand

### ISSUE THREAD

**Issue by healerz** [sebastianbergmann/phpunit#3046] opened 2018-03-22 13:51 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.2
| PHP version         | 7.1.13
| Installation Method | Composer

DataProviders get called before the execution of the first test, which leads to issues if we wanna check for a tight timespan.

To illustrate the issue:
```
class TimespanTest extends TestCase
{
    public function testWaitFor1Minute(): void
    {
        sleep(60);
    }

    /**
     * @dataProvider timespanProvider
     */
    public function testIsInTimespan(string $before, string $after): void
    {
        $now = (new \DateTime())->format('Y-m-d H:i:s');

        self::assertLessThan($now, $before);
        self::assertGreaterThan($now, $after);
    }

    public function timespanProvider(): array
    {
        $format = "Y-m-d H:i:s";
        $oneMinuteBeforeNow = (new \DateTime())->sub(new \DateInterval('PT1M'))->format($format);
        $oneMinuteAfterNow = (new \DateTime())->add(new \DateInterval('PT1M'))->format($format);

        return [
            [$oneMinuteBeforeNow, $oneMinuteAfterNow]
        ];
    } 
}
```

In my opinion this should not result in a failing test. And i do not see any benefit in executing all the data providers of the whole project beforehand.

**Comment by sebastianbergmann** [comment] 2018-03-22 14:49
Duplicate of #10.

**Closed by sebastianbergmann** 2018-03-22 14:49 UTC
