### ISSUE TITLE
Don't mark closing all output buffers as risky

### ISSUE THREAD

**Issue by mrclay** [sebastianbergmann/phpunit#2154] opened 2016-05-06 22:18 UTC
I propose `PHPUnit_Framework_RiskyTestError` only be thrown if `ob_get_level() > $this->outputBufferingLevel` (or allow some other mechanism to allow this).

I do agree that a test that does not close its _own_ output buffers should be considered risky, but code that empties all output buffers seems pretty reasonable to me.

E.g. 1: A framework wants to collect output to build a formal Response object.
E.g. 2: `TestCase::stopOutputBuffering()` empties all buffers, why is it just OK for PHPUnit to do it? ;)

If you're amenable to the idea I can send a PR.

**Comment by sebastianbergmann** [comment] 2016-09-21 13:47
Duplicate of #2101.

**Closed by sebastianbergmann** 2016-09-21 13:47 UTC
