### ISSUE TITLE
Undefined class constant COLOR_DEFAULT

### ISSUE THREAD

**Issue by donalddw** [sebastianbergmann/phpunit#1724] opened 2015-05-25 16:19 UTC
Hi,

Not sure when this started, but every time I try to run phpunit I get this error message

Fatal error: Undefined class constant 'COLOR_DEFAULT' in /usr/share/php/PHPUnit/TextUI/TestRunner.php on line 900

When I run phpunit --colors it works.

I'm on fedora and I have installed phpunit with yum install php-phpunit-PHPUnit

**Comment by sebastianbergmann** [comment] 2015-05-25 16:35
Please provide the output of `phpunit --version` and `yum info php-phpunit-PHPUnit`.

**Comment by donalddw** [comment] 2015-05-25 16:39
phpunit --version
PHPUnit 4.6.5 by Sebastian Bergmann and contributors.

yum info php-phpunit-PHPUnit
Loaded plugins: langpacks
Installed Packages
Name        : php-phpunit-PHPUnit
Arch        : noarch
Version     : 4.6.5
Release     : 1.fc21
Size        : 750 k
Repo        : installed
From repo   : updates
Summary     : The PHP Unit Testing framework
URL         : https://github.com/sebastianbergmann/phpunit
License     : BSD
Description : PHPUnit is a family of PEAR packages that supports the development of
            : object-oriented PHP applications using the concepts and methods of Agile
            : Software Development, Extreme Programming, Test-Driven Development and
            : Design-by-Contract Development by providing an elegant and robust framework
            : for the creation, execution and analysis of Unit Tests.

**Comment by sebastianbergmann** [comment] 2015-05-25 16:53
I cannot reproduce this. And as you can see below, the constant is declared:

    $ git co 4.6.5
    Note: checking out '4.6.5'.

    You are in 'detached HEAD' state. You can look around, make experimental
    changes and commit them, and you can discard any commits you make in this
    state without impacting any branches by performing another checkout.

    If you want to create a new branch to retain commits you create, you may
    do so (now or later) by using -b with the checkout command again. Example:

      git checkout -b new_branch_name

    HEAD is now at 1c54dd1... Prepare release


    $ grep COLOR_DEFAULT src/**/*.php
    src/TextUI/ResultPrinter.php:    const COLOR_DEFAULT = self::COLOR_NEVER;
    src/TextUI/ResultPrinter.php:    public function __construct($out = null, $verbose = false, $colors = self::COLOR_DEFAULT, $debug = false, $numberOfColumns = 80)
    src/TextUI/TestRunner.php:        $arguments['colors']                             = isset($arguments['colors'])                             ? $arguments['colors']                             : PHPUnit_TextUI_ResultPrinter::COLOR_DEFAULT;

**Comment by remicollet** [comment] 2015-05-25 17:47
@sebastianbergmann I confirm, no patch in fedora (except autoloader stuff).

Such strange issues (like this one) can happens when you have 2 versions of PHPunit
* one in system
* one in current project (probably an old one)

So, when you want ro tun unit test from a composer project which have "require-dev: phpunit" you need to run "vendor/bin/phpunit"

@donalddw can you please check if you are in this case.

Probably I should add a check in the launcher to check such case.

**Comment by donalddw** [comment] 2015-05-26 05:20
@remicollet This seems to have been the problem. Thank you!

**Comment by remicollet** [comment] 2015-05-26 06:50
I have reopen  https://bugzilla.redhat.com/1157910 and plan to push quickly an update in Fedora.

@sebastianbergmann I think you can close this one, which is not directly related to PHPUnit  (phpunit.phar is not affected as IIRC, all classes are preloaded)

**Comment by remicollet** [comment] 2015-05-26 07:04
@sebastianbergmann FYI https://github.com/remicollet/remirepo/commit/87b2dd66459f0f3cfedcbe367c86b06f1940e422

**Comment by remicollet** [comment] 2015-05-26 07:49
@donalddw feedback on https://admin.fedoraproject.org/updates/php-phpunit-PHPUnit-4.6.7-2.fc21 welcome.

**Comment by donalddw** [comment] 2015-05-26 08:23
@remicollet 
I did yum remove phpunit, made sure it was uninstalled and I installed the updated one

```
phpunit -v
PHPUnit 4.6.7 by Sebastian Bergmann and contributors.
```

```
phpunit UrbanAirshipTest.php 
PHP Fatal error:  Undefined class constant 'COLOR_DEFAULT' in /usr/share/php/PHPUnit/TextUI/TestRunner.php on line 900

Fatal error: Undefined class constant 'COLOR_DEFAULT' in /usr/share/php/PHPUnit/TextUI/TestRunner.php on line 900
```

When the --colors flag is used it works fine

```
../../vendor/phpunit/phpunit/phpunit UrbanAirshipTest.php
```

When used the one from the vendor directory it works fine

**Comment by remicollet** [comment] 2015-05-26 08:32
It seems you haven't remove anything.
Please try to download and install:
https://kojipkgs.fedoraproject.org//packages/php-phpunit-PHPUnit/4.6.7/2.fc21/noarch/php-phpunit-PHPUnit-4.6.7-2.fc21.noarch.rpm

**Comment by donalddw** [comment] 2015-05-26 08:39
@remicollet I think it's installed. I've reinstalled to be sure, but still the same problem.

```
sudo yum install php-phpunit-PHPUnit-4.6.7-2.fc21.noarch.rpm 
Loaded plugins: langpacks
Examining php-phpunit-PHPUnit-4.6.7-2.fc21.noarch.rpm: php-phpunit-PHPUnit-4.6.7-2.fc21.noarch
Marking php-phpunit-PHPUnit-4.6.7-2.fc21.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package php-phpunit-PHPUnit.noarch 0:4.6.7-2.fc21 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================
 Package                  Arch        Version           Repository                                     Size
============================================================================================================
Installing:
 php-phpunit-PHPUnit      noarch      4.6.7-2.fc21      /php-phpunit-PHPUnit-4.6.7-2.fc21.noarch      750 k

Transaction Summary
============================================================================================================
Install  1 Package

Total size: 750 k
Installed size: 750 k
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction (shutdown inhibited)
  Installing : php-phpunit-PHPUnit-4.6.7-2.fc21.noarch                                                  1/1 
  Verifying  : php-phpunit-PHPUnit-4.6.7-2.fc21.noarch                                                  1/1 

Installed:
  php-phpunit-PHPUnit.noarch 0:4.6.7-2.fc21
```

**Comment by remicollet** [comment] 2015-05-26 08:49
I understand:

    ../../vendor/phpunit/phpunit/phpunit UrbanAirshipTest.php

You are not in the top directory of the project.
The common practice is to have the phpunit.xml in the top directory, and run phpunit from there, and the workaround in the RPM only work in this case.

**Comment by donalddw** [comment] 2015-05-26 08:54
@remicollet Ok, thanks for your help :)

**Closed** 2015-05-26 08:53 UTC
