### ISSUE TITLE
PHP 5.4.* : PHPUnit_Framework_Exception: 'D:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by xgendrea** [sebastianbergmann/phpunit#2214] opened 2016-06-10 18:41 UTC
For my project, I created 188 Tests with 423 Assertions. This was working great in PHPUnit 5.3.*. Yesterday I upgrade to PHPUnit 5.4.4 and a lot of tests are working great but 25 are in error.
I downgrade and no errors happens. So when analyzing it could be related to @runInSeparateProcess token. The error is always the same : "PHPUnit_Framework_Exception: 'D:\Program' n'est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes." This means something like "PHPUnit_Framework_Exception: 'D:\Program' is not recognized as an internal or external command". I run PHP on Windows (installed in D:\Program Files\PHP\7.0.5, PHPUnit is installed on D:\Papagei\Site\lib\phpunit.

**Comment by jmauerhan** [comment] 2016-06-10 21:59
I have a PR for this 😊

**Comment by sebastianbergmann** [comment] 2016-06-11 05:10
Duplicate of #2211.

**Closed by sebastianbergmann** 2016-06-11 05:10 UTC
