### ISSUE TITLE
Generator data providers are not using keys

### ISSUE THREAD

**Issue by Xerkus** [sebastianbergmann/phpunit#2871] opened 2017-11-19 14:06 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.4
| PHP version         | 7.1.11
| Installation Method | Composer

Generator data providers are not using keys, resulting in description label for the data set being lost.

```php
public function someDataProvider()
{
    yield 'descriptive key' => ['values'];
}

/**
 * @dataProvider someDataProvider
 */
public function testSomething($param)
{
    $this->assertEquals('value', $param);
}
```
Keys are explicitly disabled here, if I understood the code right:
https://github.com/sebastianbergmann/phpunit/blob/f7c8195d576e2e2eef6be0a0cf9d5dd6852a2220/src/Util/Test.php#L526-L528

---
I wanted to use generators to process route definitions into data sets for several different tests
```php
    public function routeMatchingRoutesProvider()
    {
        $routes = $this->getRoutesToTest();
        foreach ($routes as $descriptionLabel => $routeDef) {
            yield $descriptionLabel => [
                $routeDef['route'], // configured route to test
                new ServerRequest([], [], new Uri($routeDef['path'])), // request
                $routeDef['offset'] ?? 0, // offset to use
                $routeDef['is_match'], // if should match
                $routeDef['params'] ?? [], // expected matched params
            ];
        }
    }
```
Turns out, description is lost, which makes generators nearly useless for my needs:
```
11) ZendTest\Router\Route\LiteralTest::testPartialMatching with data set #0
 (Closure Object (...), Zend\Diactoros\ServerRequest Object (...), 0, true, array(), 5)
Failed asserting that 4 matches expected 5.
```

**Comment by sebastianbergmann** [comment] 2017-11-27 14:13
Duplicate of #2867.

**Closed by sebastianbergmann** 2017-11-27 14:13 UTC
