### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3419] opened 2018-11-27 06:26 UTC
https://github.com/sebastianbergmann/phpunit/pull/3418#issuecomment-441767118 is not the first time that the AppVeyor configuration ran out of date (see #2880).

@helhum @IchHabRecht Does AppVeyor really need constant attention to keep working? If so, I would rather remove it (for which I would feel bad since you invested so much effort to make it initially work) unless somebody commits to keeping an eye on it.

**Comment by epdenouden** [comment] 2018-11-27 18:30
I've added a fix for this in https://github.com/sebastianbergmann/phpunit/pull/3421 to get the build working again.

**Comment by sebastianbergmann** [comment] 2018-11-28 14:20
Can you please send the AppVeyor changes in a separate pull request? Thanks! We'll also need this in the other active branches.

**Comment by epdenouden** [comment] 2018-11-28 14:21
Of course :) I already figured and opened #3423 for that reason

**Closed as completed** 2018-11-28 14:23 UTC

**Comment by weltling** [comment] 2018-11-28 20:21
@sebastianbergmann sure, i'll help where I can. @IchHabRecht, @epdenouden do i understand correctly, that you need to always fetch some latest releases? Could you please short articulate teh proposed solution? The integration between windows.php.net and php.net could be of course improved a bit, but in many cases time and security reasons are what stands in the way. Perhaps it can also be fixed an easier way, so please tell what exactly the issue is.

Thanks.

**Comment by IchHabRecht** [comment] 2018-11-28 22:09
hi @weltling,

Thanks for getting back to me. I created a gist with the content of my email. Please see https://gist.github.com/IchHabRecht/21902a244c5cd69de4e84275b276c73a

If you want I can post this anywhere else. Just let me know.

**Comment by weltling** [comment] 2018-11-29 12:40
@IchHabRecht i see, so you want the `latest` link. As it works till now, the latest versions are all to be found in https://windows.php.net/downloads/releases/. Once a new version is uploaded, the previous one is moved to https://windows.php.net/downloads/releases/archives/. I was just talking to @sAnexeh who takes care of the windows.php.net infrastructure and next week we're gonig to work on providing some kind of redirection to the latest zips.

Btw. another solution for you could be also to stick to some version and update it from time to time. I was solving it that way like here https://github.com/nikic/php-ast/blob/master/.appveyor.yml#L141. The version changes are always reflected in https://windows.php.net/downloads/releases/sha256sum.txt and a couple of other places. So yet another solution therefore were to parse the checksum file. It would be not much different from what is provided here http://php.net/releases/?json, also no `latest` links as far as i can tell.

Maybe a better way would be to include the zipballs into the package listing on php.net, that could be evaluated, too.

Regarding the PECL releases it is more complex. The integration with the PECL website is quite rudimentary. A full implementation would be sure great to have, but would take time that is hard to find. Here I can also suggest to use the REST interface of the PECL website, see https://pear.php.net/manual/en/core.rest.php. Note, that `latest.txt` might be not same as `stable.txt` there. As the REST interface is well documented, it can be reused in the same form. Otherwise, to get the Windows builds listed on the PECL REST interface, one would need to first extend the API and to implement the handling. At the moment there's neither a specification nor there was a demand. I think, some volunteers for this part would be needed, if one wants it to be integrated good. Otherwise, the suggested simpler solution to first query PECL, that would only cost one additional HTTP request from time to time.

Thanks.

**Comment by epdenouden** [comment] 2019-01-13 20:56
@weltling thanks for the update! I will update our AppVeyor settings to match :)

**Comment by sebastianbergmann** [comment] 2019-01-14 06:33
@epdenouden Thanks for taking care of this.

**Comment by epdenouden** [comment] 2019-01-14 12:06
@weltling Am I correct that the file (for example) `php-7.3-nts-Win32-VC15-x64-latest.zip` is only available as a direct link, but not shown the directory listing? I noticed that the file that is downloaded has a different name than the URL, which causes our CI to fail as it assumes the name to be the same.

I'll fix this on our end but as an end user I do find this implementation of the `some-package-latest.tgz` to be less handy than the convention of symlinking the file on the download server.

**Comment by sAnexeh** [comment] 2019-01-15 12:55
@epdenouden we've added a `latest` folder (https://windows.php.net/downloads/releases/latest/) to reflect the availability of these downloads. They're now rewritten instead of redirected in IIS so the filename will stay the same. You'll have to update the AppVeyor settings to match the new URL. 

I hope this better matches what you were looking for.

**Comment by epdenouden** [comment] 2019-01-15 13:31
@sAnexeh cool, thanks! I will update our CI config
