### ISSUE TITLE
Unbuffered TestDox printer option

### ISSUE THREAD

**Issue by epdenouden** [sebastianbergmann/phpunit#3567] opened 2019-03-18 12:38 UTC
_As a_ developer of slower integration tests
_I want to_ see prettified tests results as soon as tests are completed
_so that_ my workflow is both agile and æsthetic

## Background ##
The [buffering testdox printer](#3417) and its friend [the spinner](#3513) are [breaking some workflows](https://github.com/sebastianbergmann/phpunit/issues/3560#issuecomment-473871720) that people used to good effect.

The example from #3560 is using Testdox to get readable results while running. The actual test order is not that important, set by configuration or implied by test collection structure. My implementation of the buffering printer breaks this specific use case.

## Solution ##
Implement explicit "do not buffer result ouput" option, along the lines of #3513:
- [x] extend buffering mechanism to explicitly support always-flush
- [x] add CLI flag
- [x] add end-to-end tests voor `--enable-buffer` and `--disable-buffer` flag
- [x] add XML-configuration option
- [x] add unit test coverage for unbuffered Testdox

**Comment by rpkamp** [comment] 2019-03-26 16:42
This would be a lot simpler if the buffering were done in a decorator.

By default you apply the decorator when the tests are shuffled, unless the CLI/config indicates it shouldn't.

This has the added benefit that the decorator could decorate _any_ result printer, not just the TestDox printer. This may not be interesting for PHPUnit itself, but it might be for third party printers.

I wouldn't mind taking a stab at this if you'd like.

**Comment by BafS** [comment] 2020-02-25 13:24
Any new about this issue @epdenouden ?

**Comment by epdenouden** [comment] 2020-02-25 13:51
Yes, this issue is on hold until the new event system is ready.

Back then I did some experiments and it ended up about as hacky as the TestDox internals.

**Comment by N4M3Z** [comment] 2020-03-25 14:39
I see the issue is still marked as blocked, are there any news about the new event system?

**Comment by epdenouden** [comment] 2020-06-30 07:34
@m4rw3r The event system is still under development. @localheinz and @theseer are working on the central parts. As soon as those are (pre-release) stable I can migrate the logging and execution reordering.

**Comment by epdenouden** [comment] 2020-06-30 07:34
Also, this is under active development again as I want more logging options while working on #4302 and adjacent refactorings.

**Comment by epdenouden** [comment] 2020-07-02 09:24
![image](https://user-images.githubusercontent.com/26651359/86341392-856ddb00-bc56-11ea-8051-a923671c67aa.png)

**Closed** 2022-09-25 13:30 UTC
Labels: type/enhancement, feature/testdox

**Comment by BafS** [comment] 2022-09-25 16:21
@sebastianbergmann this PR didn't get merged https://github.com/sebastianbergmann/phpunit/pull/4346, this issue is still valid.

**Comment by sebastianbergmann** [comment] 2022-09-25 17:46
The existing TestDox implementation in PHPUnit 8.5 and PHPUnit 9.5 will not be changed. PHPUnit 10 will have an implementation of TestDox that does not have this problem.

**Comment by BafS** [comment] 2022-09-26 06:58
Okay thanks for the feedback!
