### ISSUE TITLE
8.4.2 upgrade (from 8.4.1) Broke Junit Publishing Due to Malformed XML Output

### ISSUE THREAD

**Issue by emmm-dee** [sebastianbergmann/phpunit#3929] opened 2019-11-05 22:49 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.4.2
| PHP version         | 7.2.24
| Installation Method | Composer 

#### Summary

When I run phpunit against identical pieces of code, just one with phpunit 8.4.2 and one with 8.4.1 I get different output XML structures. I'm using Jenkins and the xUnit plugin to publish. Nothing has changed in the stack besides the phpunit version. 

- If the output XML is generated with `phpunit 8.4.1` everything works fine. 
- If the XML was generated with `phpunit 8.4.2`, Junit / xUnit publisher complains and publishing fails: 
```
The file '/var/jenkins_home/workspace/Test_master/test/unitglobal.xml' is an invalid file.

At line 3 of file:/var/jenkins_home/workspace/Auth_master/test/unitglobal.xml:cvc-complex-type.3.2.2: Attribute 'warnings' is not allowed to appear in element 'testsuite'.
```

The issue is due to the `warnings=` field in the output. This did not exist before: 

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="unit/global/account" tests="29" assertions="132" errors="0" warnings="0" failures="0" skipped="0" time="2.178140">
```

#### Previous Behavior

The XML struct did not have the `warnings` field:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="unit/global/account" tests="29" assertions="132" errors="0" failures="0" skipped="0" time="2.100398">
```

#### Current Behavior

```
The file '/var/jenkins_home/workspace/Test_master/test/unitglobal.xml' is an invalid file.

At line 3 of file:/var/jenkins_home/workspace/Auth_master/test/unitglobal.xml:cvc-complex-type.3.2.2: Attribute 'warnings' is not allowed to appear in element 'testsuite'.
```

#### How to reproduce

Explained above, the codebase is closed source but the phpunit output XML has a `warnings` tag which is making Junit/xUnit choke.

**Comment by sebastianbergmann** [comment] 2019-11-06 05:51
Duplicate of #3913.

**Closed by sebastianbergmann** 2019-11-06 05:51 UTC
Labels: backward-compatibility-break, bug
