### ISSUE TITLE
Mocking invalid classes/methods marks the tests with a warning but test can actually fail

### ISSUE THREAD

**Issue by Tobion** [sebastianbergmann/phpunit#2228] opened 2016-06-23 14:30 UTC
When you try to mock a non-existing class or method phpunit will mark the test with a **warning** (ref sebastianbergmann/phpunit-mock-objects#296). A warning would mean to me that the tests works and succeeds but the coding style is bad or that it uses features that are not reliable in the future. And warnings will also not change the exit code.

But it actually doesn't execute any tests because it internally throws an exception. So anything after the "warning" is just ignored. This also means that a test might be marked as warning when it actually fails like the examples below. So warnings actually hide broken code!

```
    public function testMockNonExistingClass()
    {
        $mock = $this->createMock('FooBar');

        $this->assertTrue(false);
    }

    public function testMockNonExistingMethod()
    {
        $mock = $this->createMock(\stdClass::class);
        $mock->expects($this->any())
            ->method('__toString')
            ->will($this->returnValue(''));

        $this->assertTrue(false);
    }
```

**Comment by mcustiel** [comment] 2017-04-01 12:11
Hello. I was going through the code and it seems the TestResult class is collecting exceptions thrown from the mock generation and marking them as warnings. That is a bit confusing because the code after the failure during mock is not executed (an exception is thrown), so maybe they should be marked as error and the rest of the problems that are really warnings (the execution flow continuous) still be marked as warnings.
Portion of code where the exception is marked as warning:
```php
      catch (PHPUnit_Framework_MockObject_Exception $e) {
            $e = new PHPUnit_Framework_Warning(
                $e->getMessage()
            );

            $warning = true;
        }
```

`PHPUnit_Framework_MockObject_Exception` is extended from `PHPUnit_Framework_MockObject_RuntimeException` and `PHPUnit_Framework_MockObject_BadMethodCallException`.

The exception for the case in test `testMockNonExistingMethod` in example is thrown in `PHPUnit_Framework_MockObject_Builder_InvocationMocker::method()`

The exception for the case in test `testMockNonExistingClass` in example is throuwn in `PHPUnit_Framework_MockObject_Generator::getMock` only if we set `$allowMockingUnknownTypes` to false.

**Comment by sebastianbergmann** [comment] 2017-10-14 04:29
PHPUnit works as intended. This needs to be documented (better).

**Closed by sebastianbergmann** 2017-10-14 04:29 UTC

**Comment by Tobion** [comment] 2017-10-14 13:08
Obviously it doesn't. Either the warning should be changed to a failure. Or it cannot use exceptions for "warnings" which hide actual problems.

**Comment by Tobion** [comment] 2017-10-14 13:10
It's like saying when triggering a deprecation warning, I throw an exception which stops the program logic instead of using trigger_error.

**Comment by frncmx** [comment] 2017-12-14 12:49
As a PHP new comer, I strongly agree with @Tobion.
The default behaviour of the framework is totally unexpected.

Refactor missed the method mock call. So, we ended up with mocking the wrong method.
Skipping the test in such scenario instead of failing is not what I would expect from a test framework.
