### ISSUE TITLE
assertEquals with new lines

### ISSUE THREAD

**Issue by digilist** [sebastianbergmann/phpunit#2588] opened 2017-03-28 14:43 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.0.7
| PHP version         | 7.1.3
| Installation Method | Composer 

Consider following assertion:
```php
$this->assertEquals("foo\nbar", "foo\rbar");
```

This assertion fails with the following output:

```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'foo
 bar'
```

The output does not indicate that there is a wrong new line character. It would be great if phpunit gives a hint about this.

**Comment by sebastianbergmann** [comment] 2017-03-28 14:53
Duplicate of #1804.

**Closed by sebastianbergmann** 2017-03-28 14:53 UTC
