### ISSUE TITLE
Unexpected failed date matching

### ISSUE THREAD

**Issue by rrehbein** [sebastianbergmann/phpunit#2923] opened 2017-12-15 21:09 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.5, 5.7.25
| PHP version         | 7.1.11
| Installation Method | Composer

Got a random failure when checking if two dates were equal. The output in PHPUnit 6 shows no-diff. PHPUnit 5 shows a no-difference diff.

To isolate my issue, I started a new project with only phpunit/phpunit and the test file.

Output of `composer info -D`
```
$ composer info -D
phpunit/phpunit 6.5.5 The PHP Unit Testing framework.
```

Output of `composer info` (without the `-D`)
```
$ composer.phar info | sort
doctrine/instantiator              1.0.5 A small, lightweight utility to instantiate objects in PHP without invoking their constructors
myclabs/deep-copy                  1.7.0 Create deep copies (clones) of your objects
phar-io/manifest                   1.0.1 Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    1.0.1 Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1 Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.2.0 With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBl...
phpdocumentor/type-resolver        0.4.0
phpspec/prophecy                   1.7.3 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          5.3.0 Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.5 FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1 Simple template engine.
phpunit/php-timer                  1.0.9 Utility class for timing
phpunit/php-token-stream           2.0.2 Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    6.5.5 The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       5.0.5 Mock Object library for PHPUnit
sebastian/code-unit-reverse-lookup 1.0.1 Looks up which function or method a line of code belongs to
sebastian/comparator               2.1.0 Provides the functionality to compare PHP values for equality
sebastian/diff                     2.0.1 Diff implementation
sebastian/environment              3.1.0 Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0 Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0 Snapshotting of global state
sebastian/object-enumerator        3.0.3 Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1 Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0 Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0 Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1 Library that helps with managing the version number of Git-hosted PHP projects
theseer/tokenizer                  1.1.0 A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.2.0 Assertions to validate method input/output with nice error messages.
```

```php
<?php

class TestDate extends PHPUnit\Framework\TestCase
{
    /**
     * @dataProvider sampleMoments
     */
    public function testDateCompare($moment)
    {
        $a = new \DateTime('@'.$moment);
        $a->setTimezone(new \DateTimeZone('America/Chicago'));

        $b = new \DateTime('@'.$moment);
        $b->setTimezone(new \DateTimeZone('America/Chicago'));

        $this->assertEquals($a, $b);
    }

    public function sampleMoments()
    {
        $moment = 309943777;

        return [
            'passes' => [
                $moment + 3600,
            ],
            'fails' => [
                $moment,
            ],
        ];
    }
}
```

Result:
```
$ vendor/bin/phpunit test.php
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.

.F                                                                  2 / 2 (100%)

Time: 12 ms, Memory: 4.00MB

There was 1 failure:

1) TestDate::testDateCompare with data set "fails" (309943777)
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual

/tmp/test/test.php:16

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

**Comment by sebastianbergmann** [comment] 2017-12-16 05:02
That single line is not the complete output of `composer info -D | sort`.

**Comment by sebastianbergmann** [comment] 2017-12-16 05:05
### PHPUnit 5.7
```
PHPUnit 5.7.25-19-gf43b6f41d by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.0 with Xdebug 2.6.0alpha1

.F                                                                  2 / 2 (100%)

Time: 21 ms, Memory: 4.00MB

There was 1 failure:

1) Test::testOne with data set "fails" (309943777)
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual
@@ @@
 1979-10-28T01:29:37.000000-0600

/home/sb/Test.php:15

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```
### PHPUnit 6.5
```
phpunit --verbose Test
PHPUnit 6.5.4-17-g51cae630f by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.0 with Xdebug 2.6.0alpha1

.F                                                                  2 / 2 (100%)

Time: 22 ms, Memory: 4.00MB

There was 1 failure:

1) Test::testOne with data set "fails" (309943777)
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual

/home/sb/Test.php:15

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```
### PHPUnit 7.0
```
PHPUnit 7.0-g338d1ab37 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.0 with Xdebug 2.6.0alpha1

.F                                                                  2 / 2 (100%)

Time: 24 ms, Memory: 4.00MB

There was 1 failure:

1) Test::testOne with data set "fails" (309943777)
Failed asserting that two DateTime objects are equal.
--- Expected
+++ Actual

/home/sb/Test.php:15

FAILURES!
Tests: 2, Assertions: 2, Failures: 1.
```

**Comment by sebastianbergmann** [comment] 2017-12-16 05:30
The different diff outputs are related to different versions of `sebastian/diff` being used by PHPUnit 5 and PHPUnit 6/7.

**Comment by sebastianbergmann** [comment] 2017-12-16 05:35
This is not a bug in PHPUnit itself but in the [SebastianBergmann\Comparator\DateTimeComparator::assertEquals()](https://github.com/sebastianbergmann/comparator/blob/c42cbbec8fdcdcd0f3a9509096fe65e2d8fdbfad/src/DateTimeComparator.php#L51) method of the `sebastian/comparator` component.

For some reason, that comparison fails for two `DateTime` objects that both represent `309943777` in the `America/Chicago` timezone. This is especially strange since the [tests](https://github.com/sebastianbergmann/comparator/blob/c42cbbec8fdcdcd0f3a9509096fe65e2d8fdbfad/master/tests/DateTimeComparatorTest.php#L47) for `DateTimeComparator` include cases that are almost identical.

Maybe @derickr can spot what is wrong in the implementation of `DateTimeComparator`.

**Comment by sebastianbergmann** [comment] 2017-12-16 05:48
Simplified reproducing test case:
```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $a = new \DateTime('@309943777');
        $a->setTimezone(new \DateTimeZone('America/Chicago'));

        $b = new \DateTime('@309943777');
        $b->setTimezone(new \DateTimeZone('America/Chicago'));

        $this->assertEquals($a, $b, 0.0);
    }
}
```

**Comment by sebastianbergmann** [comment] 2017-12-16 05:50
Okay, this is weird: when the `DateTimeZone` object is passed to the constructor instead of setting it with `setTimezone()` after the `DateTime` object has been created then the test passes (as it should):
```php
<?php
class Test extends PHPUnit\Framework\TestCase
{
    public function testOne()
    {
        $a = new \DateTime('@309943777', new \DateTimeZone('America/Chicago'));

        $b = new \DateTime('@309943777', new \DateTimeZone('America/Chicago'));

        $this->assertEquals($a, $b, 0.0);
    }
}
```
```
PHPUnit 6.5.4 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 12 ms, Memory: 4.00MB

OK (1 test, 1 assertion)
```
@derickr This looks to me like an issue with `ext/date`.

**Comment by rrehbein** [comment] 2017-12-18 16:33
> That single line is not the complete output of composer info -D | sort.

Updated issue description to explain why composer-info was an unexpected single line.

**Comment by sebastianbergmann** [comment] 2017-12-19 10:00
Sorry, I should have asked for `composer info | sort` instead of `composer info -D | sort`.

**Comment by sebastianbergmann** [comment] 2017-12-19 21:08
Fixed by https://github.com/sebastianbergmann/comparator/commit/8e27e29f10f15a80216e674d99d69c55ebbf50c4 and https://github.com/sebastianbergmann/comparator/commit/329177051e1c113473530ab0486cb5e892e7e161.

Thanks! @derickr

**Closed by sebastianbergmann** 2017-12-19 21:08 UTC
Labels: bug
