### ISSUE TITLE
PhpStorm/Teamcity + PhpUnit 7.4.1 - Error in setUpBeforeClass

### ISSUE THREAD

**Issue by MaximilianKresse** [sebastianbergmann/phpunit#3364] opened 2018-10-23 06:45 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | >=7.4.0
| PHP version         | 7.1.8
| Installation Method | Composer

Sample:
```json
{
    "require": {
        "php": "^7.1"
    },

    "require-dev": {
        "phpunit/phpunit": "^7.4"
    }
}
```

```php
<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../vendor/autoload.php';

class JustATest extends TestCase
{
    public static function setUpBeforeClass(): void
    {
        throw new \RuntimeException('Something\'s not quite right!');
    }

    public function testSomething(): void
    {
        $this->fail('This cannot work!');
    }
}

```

When I run this test in phpstorm i will just get "Empty test suite." with the success icon without any failed test. Full output:
```
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

Empty test suite.


Time: 64 ms, Memory: 2.00MB


ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

Process finished with exit code 2
```

There seems to be an critical error in the teamcity logger (src/Util/Log/TeamCity.php). You added some "if (!$test instanceof TestCase) {return;}" in the last version and this also seem to trigger this error (or rather don't trigger an error). When I change the addError method to the following everything works like expected:
```php
public function addError(Test $test, \Throwable $t, float $time): void
    {
        if (!$test instanceof TestCase && !$test instanceof TestSuite) {
            return;
        }
```

I'm not sure whether this is everything to fully fix this bug. Propably the other added if-statements also have to be changed like this.

**Comment by sebastianbergmann** [comment] 2018-10-23 06:47
**ping** @SvetlanaZem

**Comment by SvetlanaZem** [comment] 2018-10-23 09:53
@sebastianbergmann Thank you! 
@wbars  Would you please take a look?

**Comment by wbars** [comment] 2018-10-24 09:49
@sebastianbergmann Why `!$test instanceof TestCase` check was introduced in the first place? As I can tell, here is flow of the problem:
 - We run test suite
 - `setUpBeforeClass` got invoked, throws an exception
 - error is nor registered in our engine singe `addError` will silently return
 - `testSomething` is not invoked

After that we got unexpected inconsistent state when we run 0 tests, but no one register at least one skipped/error/assertion and after that unexpected behaviour about the icons come in.

If `!$test instanceof TestCase` is not crucial I suggest to simply remove them. Otherwise please tell and we will try to figure something out.

**Comment by epdenouden** [comment] 2018-11-13 09:30
Checking for `instanceof TestCase` is not enough, `@dataprovider` driven tests are instances of `DataProviderTestSuite` which would be covered by `instanceof TestSuite`.

This has caused quite a few bugs and oversights for the test execution ordering. Some background in #3396.

**Comment by Bob4ever** [comment] 2018-11-14 09:31
@epdenouden Just to confirm that I'm reading your comment correctly: You're confirming that the actual code is bugged and it's not enough and that checking against ```instanceof TestCase``` and ```instanceof TestSuite``` would fixing it, correct?
Because there seems to be some [kind of confusion](https://github.com/sebastianbergmann/phpunit/pull/3400#issuecomment-438591436)...

**Comment by Bob4ever** [comment] 2018-11-20 12:50
Any life sign here? This story is kind of tiring... 
It's already a month ago and nobody seems to be really interested in this small but significant bug.

**Comment by epdenouden** [comment] 2018-11-23 14:13
This is a developer experience annoyance. Technically it is related to the TestDox reordering #3380 and the discussions about the TestListener/TestHooks in #3390, #3382.

@sebastianbergmann Proposal: if you can assign this issue to me, I will look into this and make a fix as a learning project for discussing the TestHook RFC. Together with the recent work on execution sorting and printer-based un-sorting, it will give me useful background for helping with the TestHook proposals.

**Comment by epdenouden** [comment] 2018-11-23 14:38
In other words: let me have a look at all the legacy we want to refactor out  :)

**Comment by epdenouden** [comment] 2018-11-26 10:11
@SvetlanaZem @wbars I have time to look into this in depth and have created a branch with some first tests to isolate the issues. It seems there is more than one thing going on. Different scenarios give _very_ different result outputs.

Branch: https://github.com/epdenouden/phpunit/tree/issue-3364-teamcity-missing-error

**Default and TestDox result printer do show `setUpBeforeClass` error**

🔬 Default printer example:
```
./phpunit \
  tests/end-to-end/regression/GitHub/3364/Issue3364SetupBeforeClassTest.php

✂️
There were 2 errors:

1) Issue3364SetupBeforeClassTest
RuntimeException: throw exception in setUpBeforeClass in /Users/ewout/proj/phpunit-new-order/tests/end-to-end/regression/GitHub/3364/Issue3364SetupBeforeClassTest.php:18
Stack trace:
#0 /Users/ewout/proj/phpunit-new-order/src/Framework/TestSuite.php(703): Issue3364SetupBeforeClassTest::setUpBeforeClass()
#1 /Users/ewout/proj/phpunit-new-order/src/TextUI/TestRunner.php(622): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
✂️
```

🔬TestDox example:
```
./phpunit \
  --testdox \
  tests/end-to-end/regression/GitHub/3364/Issue3364SetupBeforeClassTest.php

✂️ 
Issue3364SetupBeforeClassTest
 ✘ Error bootstapping suite (most likely in Issue3364SetupBeforeClassTest::setUpBeforeClass) [0.00 ms]
   │
   │ RuntimeException: throw exception in setUpBeforeClass in /Users/ewout/proj/phpunit-new-order/tests/end-to-end/regression/GitHub/3364/Issue3364SetupBeforeClassTest.php:18
   │ Stack trace:
   │ #0 /Users/ewout/proj/phpunit-new-order/src/Framework/TestSuite.php(703): Issue3364SetupBeforeClassTest::setUpBeforeClass()
✂️ 
```

🔬TeamCity however doesn't show anything useful...
```
./phpunit \
  --teamcity \
  tests/end-to-end/regression/GitHub/3364/Issue3364SetupBeforeClassTest.php

✂️ 
##teamcity[testCount count='2' flowId='85156']

##teamcity[testSuiteStarted name='Issue3364SetupBeforeClassTest' locationHint='php_qn:///Users/ewout/proj/phpunit-new-order/tests/end-to-end/regression/GitHub/3364/Issue3364SetupBeforeClassTest.php::\Issue3364SetupBeforeClassTest' flowId='85156']

##teamcity[testSuiteFinished name='Issue3364SetupBeforeClassTest' flowId='85156']
✂️ 
```

**Comment by wbars** [comment] 2018-11-29 10:30
@sebastianbergmann @epdenouden Please refer [my previous comment](https://github.com/sebastianbergmann/phpunit/issues/3364#issuecomment-432590599) about the source of the bug.

Since still nobody shared the details behind [introduced check](https://github.com/sebastianbergmann/phpunit/commit/be6564ea49b96b9776c53f627a49683ec2687ce5#diff-46516cb8ec446cf630723cbba025f14eR60) and commit message does't do it either it's unclear for me why it should be kept and I still suggest simply remove the check or at least patch it with `&& !$test instanceof TestSuite` as OP suggests (so from this point of view [this PR](https://github.com/sebastianbergmann/phpunit/pull/3400) looks OK to me. 

`\PHPUnit\Framework\TestResult::addError` is invoked only with `TestCase` and `TestSuite` as first argument so I don't see how this check can help TeamCity (e.g. PhpStorm) logger. If it's crucial for PHPUnit ecosystem, please share insights.

**Comment by epdenouden** [comment] 2018-11-29 11:01
@wbars Apologies I didn't make it clear in my reply, your investigation helped pinpointing the problem. I am not sure why the extra check for just `TestCase` ended up there. I will check the history and see if it related to other bugs. Seems to be just a case of codestyle fixes? The commit message just says "Fix issues identified by Phan".

In any case there needs to be an error emitted somehow about the failing fixtures. I'll come up with a fix.

**Comment by epdenouden** [comment] 2018-11-29 20:16
I think I have found a nice fix.

![image](https://user-images.githubusercontent.com/26651359/49249244-f8302800-f41b-11e8-93fb-be02582cedda.png)

**Closed** 2018-11-30 13:51 UTC
Labels: teamcity

**Comment by epdenouden** [comment] 2018-12-13 14:11
@SvetlanaZem @wbars I am working on a POC for an update to the event+logger system of PHPUnit and want to use the TeamCity format as one of the main test cases, as it is async, notices changes in TestSuite and supports parallel testing.

Can you help me get in touch with the proper contact at JetBrains?

**Comment by wbars** [comment] 2018-12-13 14:21
@epdenouden Please feel free to write an email for me: kirill.smelov at jetbrains dot com.
