### ISSUE TITLE
New build of last .phar

### ISSUE THREAD

**Issue by metfan** [sebastianbergmann/phpunit#2379] opened 2016-12-01 17:51 UTC
Hello, 

is it possible to have new build of last phar archive?

After upgrading to symfony 3.2.0 I got this error with a test:
` PHP Fatal error:  Undefined class constant 'PARSE_CONSTANT' in /home/ulrich/project                                                                                                                                /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php on line 396`

The constant PARSE_CONSTANT  comes with symfony/yaml 3.2 but the actual phpunit phar seems to be build with an older version.

Thanks to autoload I ended with this error because the Yaml class is already loaded by Phpunit.

I fix it on building myself phpunit.phar using [clue/phar-composer](https://github.com/clue/phar-composer) with command 
`php -d phar.readonly=off ./phar-composer.phar build https://github.com/sebastianbergmann/phpunit.git:dev-5.6.7`

Thank you

**Comment by sebastianbergmann** [comment] 2016-12-01 18:14
Duplicate of #2377.

**Closed by sebastianbergmann** 2016-12-01 18:14 UTC
