### ISSUE TITLE
type assertions as functions

### ISSUE THREAD

**Issue by marcosh** [sebastianbergmann/phpunit#3573] opened 2019-03-22 17:01 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.1
| PHP version         | 7.3
| Installation Method | `git clone`

I noticed that all the assertions `assertIsArray`, `assertIsBool`, ... regarding the type of a variable are implemented only as static methods and not as functions. Is there a reason for this? Could it be useful to add them?

**Comment by sebastianbergmann** [comment] 2019-03-22 17:56
Duplicate of #3570.

**Closed by sebastianbergmann** 2019-03-22 17:56 UTC
