### ISSUE TITLE
Why are the assertX methods in PHPUnit_Framework_Assert static

### ISSUE THREAD

**Issue by pjordaan** [sebastianbergmann/phpunit#1922] opened 2015-10-21 09:42 UTC
Hi, one of my colleagues uses Phpstorm as IDE and every time he opens a test he gets a red line under any call to $this->assertEquals, $this->assertThat, because those methods are static and it should be self::assertEquals.

However in the entire phpunit codebase and in all documentation it's being used as a non static method. So why are these methods static in the first place? My colleague wants to change all calls to self::assertEquals which I find a waste of time to put effort into.

**Comment by sebastianbergmann** [comment] 2015-10-21 09:44
Duplicate of  #1914.

See https://github.com/sebastianbergmann/phpunit/issues/1914#issuecomment-148407321

**Closed by sebastianbergmann** 2015-10-21 09:44 UTC
