### ISSUE TITLE
Empty code coverage report if project is not on the same harddrive as IDE

### ISSUE THREAD

**Issue by xantiva** [sebastianbergmann/phpunit#1698] opened 2015-04-28 22:10 UTC
Hello,

I first thought, my problem was caused by the Netneans IDE, but it seems, that PHPUnit is the resaon ...

https://netbeans.org/bugzilla/show_bug.cgi?id=251351

My normal environment is Netbeans on drive C: and projects, xampp with phpunit on E:. With this constellation, the code coverage results could not be displayed - the coverage log file contains no data.

For more details and test data, please look at the Netbeans BugZilla.

Thanks for your work with PHPUnit,
Mike

**Comment by sebastianbergmann** [comment] 2015-04-29 04:08
Duplicate of https://github.com/sebastianbergmann/php-code-coverage/issues/319

**Closed by sebastianbergmann** 2015-04-29 04:08 UTC
