### ISSUE TITLE
Attribute class "PHPUnit\Framework\Attributes\Test" not found

### ISSUE THREAD

**Issue by scorpion3dd** [sebastianbergmann/phpunit#5737] opened 2024-03-11 15:58 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.0.5
| PHP version         | 8.2.7
| Installation Method | Composer

#### Summary

I specify any attribute in the test and it gives an error
Attribute class "PHPUnit\Framework\Attributes\Test" not found
If the attribute is not satisfied, the test is executed

#### Current behavior

I specify any attribute in the test:
```
#[Test]
public function testValidate(string $version, string $fileName, array $parameters): void
```

#### How to reproduce

run tests

#### Expected behavior

runed tests

**Comment by sebastianbergmann** [comment] 2024-03-11 16:00
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by scorpion3dd** [comment] 2024-03-11 16:13
In file phpunit.xml:
```
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="tests/bootstrap.php"
         stopOnError="false"
         stopOnFailure="false"
         stopOnIncomplete="false"
         stopOnSkipped="false"
         colors="true"
         stderr="true"
         backupGlobals="true"
>
    <php>
        <ini name="memory_limit" value="-1"/>
        <ini name="display_errors" value="1" />
        <ini name="error_reporting" value="-1"/>
        <ini name="xdebug.mode" value="coverage"/>
        <env name="XDEBUG_MODE" value="coverage"/>
        <env name="SYMFONY_DEPRECATIONS_HELPER" value="weak" />
        <env name="KERNEL_CLASS" value="App\Kernel" />
        <env name="DOMAIN" value="http://symfony-mvc.learn.vms"/>
        <server name="APP_ENV" value="test" force="true" />
        <server name="SHELL_VERBOSITY" value="-1" />
        <server name="SYMFONY_PHPUNIT_REMOVE" value="" />
        <server name="SYMFONY_PHPUNIT_VERSION" value="11.0" />
    </php>

    <testsuites>
        <testsuite name="Unit">
            <directory>./tests/Unit</directory>
        </testsuite>
...
```

In file bootstrap.php:
```
require dirname(__DIR__).'/vendor/autoload.php';
BypassFinals::enable(bypassReadOnly: false);
set_exception_handler([new ErrorHandler(), 'handleException']);
if (file_exists(dirname(__DIR__).'/config/bootstrap.php')) {
    require dirname(__DIR__).'/config/bootstrap.php';
} elseif (method_exists(Dotenv::class, 'bootEnv')) {
    (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
}
```

In file ValidatorCommentUploadTest.php:
```
class ValidatorCommentUploadTest extends BaseKernelTestCase
{
    public const FULL_FILE_NAME = '/../data/Service/CommentService/london1.jpg';

    /** @var LoggerInterface $loggerMock */
    private LoggerInterface $loggerMock;

    /** @var ValidatorCommentUpload $validator */
    private ValidatorCommentUpload $validator;

    public function setUp(): void
    {
        parent::setUp();
        $this->loggerMock = $this->createMock(LoggerInterface::class);
        $this->validator = new ValidatorCommentUpload($this->loggerMock);
    }

    #[DataProvider('provideApiCommentUpload')]
    #[Test]
    public function testValidate(string $version, string $fileName, array $parameters): void
    {
...
```

run:
`php bin/phpunit --testsuite=Unit --filter testValidate --no-coverage --colors=always`


get result:
```
An error occurred inside PHPUnit.

Message:  Attribute class "PHPUnit\Framework\Attributes\Test" not found
Location: /var/www/back/vendor/phpunit/phpunit/src/Framework/Attributes/Test.php:20     

#0 /var/www/back/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var
/www/back/v...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('PHPUnit\\Framewo...') 
#2 /var/www/back/vendor/phpunit/phpunit/src/Metadata/Parser/AttributeParser.php(333): Re
flectionAttribute->newInstance()
#3 /var/www/back/vendor/phpunit/phpunit/src/Metadata/Parser/ParserChain.php(48): PHPUnit
\Metadata\Parser\AttributeParser->forMethod('App\\Tests\\Unit\\...', 'testGetType')     
#4 /var/www/back/vendor/phpunit/phpunit/src/Metadata/Parser/CachingParser.php(55): PHPUn
it\Metadata\Parser\ParserChain->forMethod('App\\Tests\\Unit\\...', 'testGetType')       
#5 /var/www/back/vendor/phpunit/phpunit/src/Metadata/Api/DataProvider.php(53): PHPUnit\M
etadata\Parser\CachingParser->forMethod('App\\Tests\\Unit\\...', 'testGetType')
#6 /var/www/back/vendor/phpunit/phpunit/src/Framework/TestBuilder.php(40): PHPUnit\Metad
ata\Api\DataProvider->providedData('App\\Tests\\Unit\\...', 'testGetType')
#7 /var/www/back/vendor/phpunit/phpunit/src/Framework/TestSuite.php(476): PHPUnit\Framew
ork\TestBuilder->build(Object(ReflectionClass), 'testGetType', Array)
#8 /var/www/back/vendor/phpunit/phpunit/src/Framework/TestSuite.php(118): PHPUnit\Framew
ork\TestSuite->addTestMethod(Object(ReflectionClass), Object(ReflectionMethod), Array)  
#9 /var/www/back/vendor/phpunit/phpunit/src/Framework/TestSuite.php(210): PHPUnit\Framew
ork\TestSuite::fromClassReflector(Object(ReflectionClass), Array)
#10 /var/www/back/vendor/phpunit/phpunit/src/Framework/TestSuite.php(240): PHPUnit\Frame
work\TestSuite->addTestSuite(Object(ReflectionClass), Array)
#11 /var/www/back/vendor/phpunit/phpunit/src/TextUI/Configuration/Xml/TestSuiteMapper.ph
p(103): PHPUnit\Framework\TestSuite->addTestFile('/var/www/back/t...', Array)
#12 /var/www/back/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(7
2): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map('/var/www/back/p...', Object(PH
PUnit\TextUI\Configuration\TestSuiteCollection), 'Unit', '')
#13 /var/www/back/vendor/phpunit/phpunit/src/TextUI/Application.php(339): PHPUnit\TextUI
\Configuration\TestSuiteBuilder->build(Object(PHPUnit\TextUI\Configuration\Configuration
))
#14 /var/www/back/vendor/phpunit/phpunit/src/TextUI/Application.php(109): PHPUnit\TextUI
\Application->buildTestSuite(Object(PHPUnit\TextUI\Configuration\Configuration))        
#15 /var/www/back/bin/phpunit(118): PHPUnit\TextUI\Application->run(Array)
#16 {main}
```

Could we communicate via Skype, for example, I would demonstrate everything in screen sharing mode in 5 minutes?

**Comment by sebastianbergmann** [comment] 2024-03-11 16:15
I am sorry, but that is neither self-contained nor minimal.

**Comment by scorpion3dd** [comment] 2024-03-11 16:19
Excuse me please, but what do you mean by a minimal, self-contained, reproducible test case that demonstrates the problem?
Please specify in more detail what I need to send?

**Comment by sebastianbergmann** [comment] 2024-03-11 16:21
A self-contained, reproducible test case is a minimal example that reproduces the issue that I can test with as-is. Minimal means without third-party wrappers around / extensions for PHPUnit such as Symfony's PHPUnit Bridge, for example.

**Comment by scorpion3dd** [comment] 2024-03-11 16:38
I deleted symfony/phpunit-bridge

All my file composer.json:
{
    "name": "symfony-demo/simple-application",
    "description": "Demo",
    "type": "project",
    "license": "BSD-3-Clause",
    "keywords": [
        "symfony",
        "mvc",
        "skeleton",
        "framework"
    ],
    "homepage": "https://github.com/",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=8.2",
        "ext-amqp": "*",
        "ext-ctype": "*",
        "ext-gd": "*",
        "ext-iconv": "*",
        "ext-intl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "ext-mongodb": "*",
        "ext-pdo": "*",
        "ext-redis": "*",
        "ext-xmlwriter": "*",
        "ext-fileinfo": "*",
        "api-platform/core": "*",
        "beberlei/doctrineextensions": "*",
        "blackfire/php-sdk": "*",
        "blackfireio/blackfire-symfony-meta": "*",
        "doctrine/annotations": "*",
        "doctrine/doctrine-bundle": "*",
        "doctrine/doctrine-migrations-bundle": "*",
        "doctrine/mongodb-odm": "*",
        "doctrine/mongodb-odm-bundle": "*",
        "doctrine/orm": "*",
        "easycorp/easyadmin-bundle": "*",
        "fakerphp/faker": "*",
        "gesdinet/jwt-refresh-token-bundle": "*",
        "imagine/imagine": "*",
        "knplabs/knp-paginator-bundle": "*",
        "lexik/jwt-authentication-bundle": "*",
        "nelmio/cors-bundle": "*",
        "nesbot/carbon": "*",
        "phpdocumentor/reflection-docblock": "*",
        "phpstan/phpdoc-parser": "*",
        "sendgrid/sendgrid": "*",
        "sensio/framework-extra-bundle": "*",
        "symfony/amqp-messenger": "*",
        "symfony/asset": "*",
        "symfony/console": "*",
        "symfony/doctrine-messenger": "*",
        "symfony/dotenv": "*",
        "symfony/expression-language": "*",
        "symfony/flex": "*",
        "symfony/form": "*",
        "symfony/framework-bundle": "*",
        "symfony/google-mailer": "*",
        "symfony/http-client": "*",
        "symfony/intl": "*",
        "symfony/mailer": "*",
        "symfony/mime": "*",
        "symfony/monolog-bundle": "*",
        "symfony/notifier": "*",
        "symfony/process": "*",
        "symfony/property-access": "*",
        "symfony/property-info": "*",
        "symfony/runtime": "*",
        "symfony/security-bundle": "*",
        "symfony/sendgrid-mailer": "*",
        "symfony/serializer": "*",
        "symfony/slack-notifier": "*",
        "symfony/string": "*",
        "symfony/translation": "*",
        "symfony/twig-bundle": "*",
        "symfony/ux-chartjs": "*",
        "symfony/validator": "*",
        "symfony/web-link": "*",
        "symfony/webpack-encore-bundle": "*",
        "symfony/workflow": "*",
        "symfony/yaml": "*",
        "symfonycorp/platformsh-meta": "*",
        "twig/cssinliner-extra": "*",
        "twig/extra-bundle": "*",
        "twig/inky-extra": "*",
        "twig/intl-extra": "*",
        "twig/string-extra": "*",
        "twig/twig": "*",
        "vich/uploader-bundle": "*",
        "webonyx/graphql-php": "*"
    },
    "config": {
        "allow-plugins": {
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*"
    },
    "scripts": {
         "check-phpunit-filter": "php bin/phpunit --testsuite=Unit --filter testValidate --no-coverage --colors=always",

        "check-phpunit-unit-no-coverage": [
            "Composer\\Config::disableProcessTimeout",
            "php vendor/phpunit/phpunit/phpunit --testsuite=Unit --no-coverage --configuration=/var/www/back/phpunit.xml --colors=always"
        ],

        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": "true",
            "require": "*",
            "docker": true
        }
    },
    "require-dev": {
        "ext-curl": "*",
        "dama/doctrine-test-bundle": "*",
        "dg/bypass-finals": "*",
        "doctrine/doctrine-fixtures-bundle": "*",
        "phpmd/phpmd": "*",
        "phpstan/phpstan": "*",
        "phpstan/phpstan-doctrine": "*",
        "phpstan/phpstan-phpunit": "*",
        "phpunit/php-code-coverage": "*",
        "phpunit/php-invoker": "*",
        "phpunit/phpunit": "*",
        "roave/psalm-html-output": "*",
        "squizlabs/php_codesniffer": "*",
        "symfony/browser-kit": "*",
        "symfony/css-selector": "*",
        "symfony/debug-bundle": "*",
        "symfony/maker-bundle": "*",
        "symfony/panther": "*",
        "symfony/stopwatch": "*",
        "symfony/web-profiler-bundle": "*",
        "vimeo/psalm": "*"
    }
}

**Comment by scorpion3dd** [comment] 2024-03-11 16:42
My file bootstrap.php:
```
declare(strict_types=1);

use DG\BypassFinals;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\ErrorHandler\ErrorHandler;

require dirname(__DIR__).'/vendor/autoload.php';

BypassFinals::enable(bypassReadOnly: false);
set_exception_handler([new ErrorHandler(), 'handleException']);
if (file_exists(dirname(__DIR__).'/config/bootstrap.php')) {
    require dirname(__DIR__).'/config/bootstrap.php';
} elseif (method_exists(Dotenv::class, 'bootEnv')) {
    (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
}
```

**Comment by sebastianbergmann** [comment] 2024-03-11 16:43
This is still not minimal. You are using `DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension` and `DG\BypassFinals`. Either of which could be interfering with PHPUnit's proper operation.

As I cannot reproduce your issue and do not have the time to debug your environment with you, sorry, I can only close this issue.

**Closed by sebastianbergmann** 2024-03-11 16:43 UTC
Labels: type/bug, status/waiting-for-feedback
