### ISSUE TITLE
Tests function prefix

### ISSUE THREAD

**Issue by lucasmichot** [sebastianbergmann/phpunit#2081] opened 2016-02-17 14:04 UTC
Hello @sebastianbergmann,
For now PHPUnit allows per default to run tests which name starts with `test` or with the `@test` docblock.
Nevertheless, it happens that all functions in a suite are prefixed another way (eg. `it_should_...`).

Don't you think a `testPrefix` option would make sense ?
The following option could for instance be set in the configuration file as:

```xml
<testsuite name="My Test Suite">
    <directory testPrefix="it_should_" suffix="Test.php" phpVersion="5.3.0" phpVersionOperator=">=">/path/to/files</directory>
    <file testPrefix="it_should_" phpVersion="5.3.0" phpVersionOperator=">=">/path/to/MyTest.php</file>
   <exclude>/path/to/files/exclude</exclude>
</testsuite>
```

It would probably imply a modification of `\PHPUnit_Framework_TestSuite::isTestMethod` method.

**Comment by sebastianbergmann** [comment] 2016-02-17 14:06
Duplicate of #2047

**Closed by sebastianbergmann** 2016-02-17 14:06 UTC
