### ISSUE TITLE
phpunit.xsd is not valid

### ISSUE THREAD

**Issue by maikgreubel** [sebastianbergmann/phpunit#2079] opened 2016-02-14 09:56 UTC
In line 20 whitelist is duplicated in choice and causes this validation error in eclipse:

    cos-nonambig: whitelist and whitelist (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.

**Comment by sebastianbergmann** [comment] 2016-02-22 21:05
Duplicate of #1961.

**Closed by sebastianbergmann** 2016-02-22 21:05 UTC
