### ISSUE TITLE
Allow multiple directories for code coverage

### ISSUE THREAD

**Issue by jaesung2061** [sebastianbergmann/phpunit#3322] opened 2018-10-03 19:46 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.3.5
| PHP version         | 7.2.9
| Installation Method | Composer

I have two directories that I need to check code coverage for. However, there doesn't seem to be a way to include both directories. Attempting to do so causes some kind of auto-loading error.

Example config:

    <?xml version="1.0" encoding="UTF-8"?>
    <phpunit backupGlobals="false"
             backupStaticAttributes="false"
             bootstrap="vendor/autoload.php"
             colors="true"
             convertErrorsToExceptions="true"
             convertNoticesToExceptions="true"
             convertWarningsToExceptions="true"
             processIsolation="false"
             stopOnFailure="false">
        <testsuites>
            <testsuite name="Unit">
                <directory suffix="Test.php">./tests/Unit</directory>
            </testsuite>
    
            <testsuite name="Feature">
                <directory suffix="Test.php">./tests/Feature</directory>
            </testsuite>
    
            <testsuite name="Modules">
                <directory suffix="Test.php">./modules</directory>
            </testsuite>
        </testsuites>
        <filter>
            <whitelist processUncoveredFilesFromWhitelist="true">
                <directory suffix=".php">./app</directory>
                <directory suffix=".php">./modules</directory>
            </whitelist>
        </filter>
        <logging>
            <log type="coverage-html" target="./tests/report" lowUpperBound="35"
                 highLowerBound="70"/>
        </logging>
        <php>
            <env name="APP_ENV" value="testing"/>
            <env name="BCRYPT_ROUNDS" value="4"/>
            <env name="CACHE_DRIVER" value="array"/>
            <env name="SESSION_DRIVER" value="array"/>
            <env name="QUEUE_CONNECTION" value="sync"/>
            <env name="MAIL_DRIVER" value="array"/>
        </php>
    </phpunit>

Notice the two directories `./app` and `./modules`. The `./modules` line is causing errors.

**Comment by sebastianbergmann** [comment] 2018-10-04 03:40
Whitelisting multiple directories for code coverage works just fine. Do note, though, that all whitelisted files will be included because you set `processUncoveredFilesFromWhitelist="true"`. This is likely the cause for the problem you are experiencing (because you likely include files that not only contain class/interface/trait declarations).

**Closed by sebastianbergmann** 2018-10-04 03:40 UTC
