### ISSUE TITLE
Backward incompatible change in PHPUnit 6.5

### ISSUE THREAD

**Issue by frederikbosch** [sebastianbergmann/phpunit#2892] opened 2017-12-01 12:10 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.0
| PHP version         | 7.1.12
| Installation Method | Composer

Version 6.5.0 contains backward incompatible changes due to the upgrade of `phpunit-mock-objects
` from version 4 to 5. See bug report [#388](https://github.com/sebastianbergmann/phpunit-mock-objects/issues/388) in that repository. Since the functionality of that library is directly available in PHPUnit, version 6.5.0 should have been version 7.0.0. And since it is not, more users will hit the problem. Therefore I think it should be at least considered to reverse to the old behaviour.

**Comment by weierophinney** [comment] 2017-12-01 16:34
I can confirm; see this job: https://travis-ci.org/zendframework/zend-session/jobs/310112861

In that build, the lockfile is pinned to a 6.2 series phpunit and 5.0 series of phpunit-mock-objects. The linked job does a `composer update`, which pulls in PHPUnit 6.5.1 and phpunit-mock-objects 5.0.2, and I then get two errors due to missing interfaces used in typehints.

I attempted aliasing the 4.0.1 interface name to the 5.0.2 interface name, but then had signature errors instead.

I'd argue that PHPUnit 6.5 should continue pinning to the phpunit-mock-objects 4 series.

**Comment by sebastianbergmann** [comment] 2017-12-01 17:35
Duplicate of https://github.com/sebastianbergmann/phpunit-mock-objects/issues/388

**Closed by sebastianbergmann** 2017-12-01 17:35 UTC
