### ISSUE TITLE
[BC Break] PHP Warning:  in_array() expects parameter 2 to be array, string given in vendor/phpunit/phpunit/src/Util/Configuration.php on

### ISSUE THREAD

**Issue by BorisMorel** [sebastianbergmann/phpunit#2493] opened 2017-02-09 09:59 UTC
Hi,

With the new tagged release 5.7.12, my testsuite failed now due to a parameter error for in_array().

My testsuites are writing as is:
```xml
<testsuites>
    <testsuite name="main">
        <file>../vendor/NS/Bundle/Tests/Controller/ApplicationControllerTest.php</file>
        [...]
    <testsuite>
<testsuites>
```

and launch with:
```bash
php vendor/phpunit/phpunit/phpunit -c app/ --testsuite=main --debug
```

Any informations about this ?

Regards,
Boris.

**Comment by rentalhost** [comment] 2017-02-09 10:37
Can you post too the error log with all calls?

**Comment by BorisMorel** [comment] 2017-02-09 10:40
```plain
PHP Warning:  in_array() expects parameter 2 to be array, string given in /vendor/phpunit/phpunit/src/Util/Configuration.php on line 977
PHP Stack trace:
PHP   1. {main}() /vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /vendor/phpunit/phpunit/src/TextUI/Command.php:118
PHP   4. PHPUnit_TextUI_Command->handleArguments() /vendor/phpunit/phpunit/src/TextUI/Command.php:129
PHP   5. PHPUnit_Util_Configuration->getTestSuiteConfiguration() /vendor/phpunit/phpunit/src/TextUI/Command.php:787
PHP   6. PHPUnit_Util_Configuration->getTestSuite() /vendor/phpunit/phpunit/src/Util/Configuration.php:876
PHP   7. in_array() /vendor/phpunit/phpunit/src/Util/Configuration.php:977
```

**Comment by rentalhost** [comment] 2017-02-09 10:45
Seems to be [fixed on 6.0](https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/Configuration.php#L907), but [not on 5.7](https://github.com/sebastianbergmann/phpunit/blob/5.7.12/src/Util/Configuration.php#L927).

**Comment by BorisMorel** [comment] 2017-02-09 10:46
Ok but why this bug is only since 5.7.12 ?

**Comment by rentalhost** [comment] 2017-02-09 10:48
I guess that it should be fixed on 5.7.12 too (ping @sebastianbergmann), 5.7.11 do works fine? Lasts changes on this part of code was been done about +3 years, then maybe all 5.7 is affected.

**Comment by BorisMorel** [comment] 2017-02-09 10:50
Latest commit (6 feb 2017) change this ...

**Comment by rentalhost** [comment] 2017-02-09 10:53
Yeah, you are right (_by some strange reason the git blame is reporting 5 years!_). Seems to be the cause of this issue.

**Closed** 2017-02-10 09:07 UTC
Labels: 5.7, bug
