### ISSUE TITLE
Missing failOnIncomplete and failOnSkipped configuration parameters

### ISSUE THREAD

**Issue by morozov** [sebastianbergmann/phpunit#4101] opened 2020-02-16 21:30 UTC
As a test suite maintainers, I'd like to prevent developers from marking tests incomplete. In large enterprise codebases, often, tests are marked as such because their failure doesn't indicate a real problem but instead is a symptom of poor test or code quality. Once marked as incomplete, these tests are never taken care of and effectively become dead code.

It would be nice to have the `failOnIncomplete` XML configuration parameter and probably a corresponding command-line switch for consistency.

As for `failOnSkipped`, I don't have a use case for this, it was mentioned in https://github.com/sebastianbergmann/phpunit/issues/4099#issuecomment-586744416.

**Comment by sebastianbergmann** [comment] 2020-02-17 05:50
Duplicate of #4100.

**Closed by sebastianbergmann** 2020-02-17 05:50 UTC
Labels: type/enhancement
