### ISSUE TITLE
Infinite loop when throws a "PHP Warning" and "PHP Fatal error"

### ISSUE THREAD

**Issue by greg-md** [sebastianbergmann/phpunit#2698] opened 2017-05-31 09:14 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.1.4
| PHP version         | 7.1.0
| Installation Method | Composer

The next example should throw a "PHP Warning" and "PHP Fatal error" but instead it goes into a infinite loop and the process never ends.

```php
<?php

class BugTest extends \PHPUnit\Framework\TestCase
{
    public function testSchouldThrowAFatalError()
    {
        call_user_func_array(function (&$foo, \stdClass $class) {

        }, ['foo']);
    }
}
```

Console log:

```
Grigoriis-MacBook-Pro:php-framework greg$ vendor/bin/phpunit --colors
PHPUnit 6.1.4 by Sebastian Bergmann and contributors.

.
```

**Comment by sebastianbergmann** [comment] 2017-06-01 07:33
I cannot reproduce this:
```
$ cat BugTest.php 
<?php
class BugTest extends \PHPUnit\Framework\TestCase
{
    public function testSchouldThrowAFatalError()
    {
        call_user_func_array(function (&$foo, \stdClass $class) {

        }, ['foo']);
    }
}
```
```
$ phpunit BugTest
PHPUnit 6.1.4 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 18 ms, Memory: 4.00MB

There was 1 error:

1) BugTest::testSchouldThrowAFatalError
Parameter 1 to BugTest::{closure}() expected to be a reference, value given

/home/sb/BugTest.php:8

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by greg-md** [comment] 2017-06-01 16:55
Hm. Yeah, try using a namespace:

```php
namespace Foo;

use PHPUnit\Framework\TestCase;

class BugTest extends TestCase
{
    public function testSchouldThrowAFatalError()
    {
        call_user_func_array(function (&$foo, \stdClass $class) {

        }, ['foo']);
    }
}
```

**Comment by sebastianbergmann** [comment] 2017-06-01 18:16
```
$ cat BugTest.php 
<?php
namespace Foo;

use PHPUnit\Framework\TestCase;

class BugTest extends TestCase
{
    public function testSchouldThrowAFatalError()
    {
        call_user_func_array(function (&$foo, \stdClass $class) {

        }, ['foo']);
    }
}
```
```
$ phpunit BugTest
PHPUnit 6.1.4 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 26 ms, Memory: 4.00MB

There was 1 error:

1) Foo\BugTest::testSchouldThrowAFatalError
Parameter 1 to Foo\BugTest::Foo\{closure}() expected to be a reference, value given

/home/sb/BugTest.php:12

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Comment by greg-md** [comment] 2017-06-01 19:03
Looks like the problem could be only on php version `7.1.0` because on `7.1.5` it works good. I will investigate more on that.

**Comment by greg-md** [comment] 2017-06-01 19:14
Yeah, the problem is only on php versions `7.1.0`, `7.1.1`, `7.1.2`, `7.1.3`. The Travis CI also goes in loop. https://travis-ci.org/greg-md/php-framework/builds/238468137

**Comment by sebastianbergmann** [comment] 2017-06-02 05:42
So then it's a bug in PHP and one that has been fixed. Closing this.

**Closed by sebastianbergmann** 2017-06-02 05:42 UTC

**Comment by greg-md** [comment] 2017-06-02 05:58
Hm. I was thinking it is not a php bug, because outside of the test it throws errors as expected. Only when running into a phpunit test it is looping and only when there is a namespace.

Looking into the `7.1.3` [changelog](http://www.php.net/ChangeLog-7.php#7.1.3) I see that there was fixed one segmentation fault bug that doesn't terminate the process.

https://bugs.php.net/bug.php?id=74164
