### ISSUE TITLE
AssertContains : $ignorecase doesn't work

### ISSUE THREAD

**Issue by Tominounet** [sebastianbergmann/phpunit#3315] opened 2018-09-27 07:55 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.13
| PHP version         | 7.2
| Installation Method | PHAR

I'm using and learning how to test my code with PHPUnit. I had some test to make, so I can understand some asserts. Then I tried this one : 

![image](https://user-images.githubusercontent.com/26654281/46130896-b2e45400-c23a-11e8-802f-11a05e7728c5.png)

So I expected this test to be ok, but...

![image](https://user-images.githubusercontent.com/26654281/46130947-cc859b80-c23a-11e8-8504-f521044cde08.png)

It seems the $ignorecase parameter doesn't work, true or false doesn't change anything. Is it normal ?

**Comment by sebastianbergmann** [comment] 2018-09-27 19:31
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting. Do not use screenshots of code.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by mkasberg** [comment] 2018-10-01 04:00
I'm not sure this is actually a bug. I think the code is behaving more or less as expected, and the behavior is documented in the [PHPUnit documentation](https://phpunit.readthedocs.io/en/7.3/assertions.html#assertcontains) (for both 7 and [6.5](https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertContains)).

`assertContains()` has 2 documented forms:

* `assertContains(string $needle, string $haystack[, string $message = '', boolean $ignoreCase = false])` which accepts a string `$haystack` and a 4th parameter `$ignoreCase`
* `assertContains(mixed $needle, Iterator|array $haystack[, string $message = ''])`, which accepts an array `$haystack` but **does not** take a 4th parameter for case sensitivity.

In your example, because your second parameter is an array, PHPUnit assumes you are using the "array" form of the method, and ignores the `$ignoreCase` parameter.

Perhaps there is some small room for improvement here. PHPUnit could throw an IllegalArgumentException (or similar) in `Framework/Assert.php` if `$ignoreCase=true` was passed and the second argument is not a string. I think it would be relatively easy for me to propose some changes along these lines in a pull request and we can see what everyone thinks.

**Comment by sebastianbergmann** [comment] 2018-11-16 09:43
No feedback, closing.

**Closed by sebastianbergmann** 2018-11-16 09:43 UTC
Labels: waiting-for-reproducing-example

**Comment by epdenouden** [comment] 2018-11-16 10:42
@sebastianbergmann looks like there is an example in the related pull request: https://github.com/sebastianbergmann/phpunit/pull/3317
