### ISSUE TITLE
returnValueMap return null when key to match is object

### ISSUE THREAD

**Issue by karborator** [sebastianbergmann/phpunit#4008] opened 2020-01-08 09:31 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | PHPUnit 8.5.0
| PHP version         | 7.3
| Installation Method | Composer 

#### Summary
This is not related to default null arguments.

I found same issue using it even when method doesn't have defaults null

```
    $dummyAccountID = new ID();
    $dummyClientID = new ID();
    $dummySiteID = new ID();

  $this->expectMultipleGetLegacyIDCalls(6, [
            [$dummyAccountID , 1],
            [$dummyClientID , 2],
            [$dummySiteID , 3],
        ]);

    private function expectMultipleGetLegacyIDCalls($numCalls, $returnValueMap) {
        $this->mock
            ->expects($this->exactly($numCalls))
            ->method('getLegacyID')
            ->will($this->returnValueMap($returnValueMap));
    }

 public function getLegacyID(ID $id){ ... }
```

#### Previous Behavior

On phpuni4 the method "getLegacyID" was returning proper integers from the map instead null 
```
   [$dummyAccountID , 1],
            [$dummyClientID , 2],
            [$dummySiteID , 3],
```
  

#### Current Behavior

On phpuni8 the method "getLegacyID" returns null per dummyAccountID , dummyClientID , dummySiteID  instead the given integers from the map 

#### How to reproduce

Create map from new instance of object and integers to return then pass it to 
``` ->will($this->returnValueMap($returnValueMap));  ``` 

```
  [$dummyAccountID , 1],
            [$dummyClientID , 2],
            [$dummySiteID , 3],
```

**Comment by sebastianbergmann** [comment] 2020-01-08 09:36
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by karborator** [comment] 2020-01-08 10:26
While trying to provide test I found whats the issue.
I'm not using the original method ```createMock``` instead I have proxy to phpunit4 ```getMock``` 
```
 public function getMock(...$args) {
            if (!$this->mockGenerator) {
                $this->mockGenerator = new MockGenerator;
            }

            $args[4] = false;//phpunit4 $callOriginalConstructor default is true but phpunit8 createMock is "disableOriginalConstructor"
            $mockObject = $this->mockGenerator->getMock(
                ...$args
            );

            $this->registerMockObject($mockObject);

            return $mockObject;
		}
```


In my opinion its related to  cloning the original object:
```Invocation.php:83:    $this->parameters[$key] = $this->cloneObject($value);```


Test is:

```
    public function testInvocationClone()
    {
        $dummyAccountID = new \stdClass();
        $dummyClientID = new \stdClass();
        $dummySiteID = new \stdClass();

        $returnValueMap = [
            [$dummyAccountID, 1],
            [$dummyClientID, 2],
            [$dummySiteID, 3],
        ];

        $mock = $this->getMock(A::class,array(), array(), '',
            false, false, false);
        $mock->expects($this->any())
            ->method('test')
            ->will($this->returnValueMap($returnValueMap));

        $this->assertEquals(1, $mock->test($dummyAccountID));
        $this->assertEquals(2, $mock->test($dummyClientID));
        $this->assertEquals(3, $mock->test($dummySiteID));
    }

PHPUnit 8.5.0 by Sebastian Bergmann and contributors.

Warning:       Invocation with class name is deprecated

F                                                                   1 / 1 (100%)

Time: 1.21 seconds, Memory: 32.16 MB

There was 1 failure:

1) LogicNow\Alerting\Mappers\AgentlessOutagesByDeviceMapperTest::testInvocationClone
Failed asserting that null matches expected 1.

/var/www/vhosts/server/classlib/Alerting/Test/Mappers/AgentlessOutagesByDeviceMapperTest.php:104

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```


And when I change to use ```createMock```

````
 public function testInvocationClone()
    {
        $dummyAccountID = new \stdClass();
        $dummyClientID = new \stdClass();
        $dummySiteID = new \stdClass();

        $returnValueMap = [
            [$dummyAccountID, 1],
            [$dummyClientID, 2],
            [$dummySiteID, 3],
        ];

        $mock = $this->createMock(A::class);
        $mock->expects($this->any())
            ->method('test')
            ->will($this->returnValueMap($returnValueMap));

        $this->assertEquals(1, $mock->test($dummyAccountID));
        $this->assertEquals(2, $mock->test($dummyClientID));
        $this->assertEquals(3, $mock->test($dummySiteID));
    }


.                                                                   1 / 1 (100%)

Time: 1.26 seconds, Memory: 32.16 MB

OK (1 test, 3 assertions)
```

**Comment by jaapio** [comment] 2020-05-30 20:50
The problem is probably in the `\PHPUnit\Framework\MockObject\Stub\ReturnValueMap` this class is doing the following check:

```
            if ($invocation->getParameters() === $map) {
                return $return;
            }
```
in the provided example testcase the `$map` contains `[$dummyAccountID]` 

php will do a strict check on the objects. `===` means that the object should be the same. not equal so using `ReturnValueMap` will not work in this case. The only way I know currently is using a combination of `withConsecutive` with `willReturnOnConsecutiveCalls` but this will require the calls in a certain order. 

I think this is related to #4255 and #4026.

**Comment by sebastianbergmann** [comment] 2020-06-08 08:40
No feedback, closing.

**Closed by sebastianbergmann** 2020-06-08 08:40 UTC
Labels: feature/test-doubles, status/waiting-for-feedback, type/backward-compatibility, type/bug
