### ISSUE TITLE
PHPUnit 7.0.0 could not automatically create code coverage report folders

### ISSUE THREAD

**Issue by KanDisheng** [sebastianbergmann/phpunit#2985] opened 2018-02-02 06:22 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.0.0
| PHP version         | 7.2.1
| Installation Method | Composer / PHAR

When I generate code coverage report in Clover XML format, there was an error:

```
PHP Fatal error:  Uncaught RuntimeException: Directory "Some Path" was not created
```

The version less than 7.0.0, PHPUnit could automatically create folders, PHPUnit 7.0.0 could not.

**Comment by sebastianbergmann** [comment] 2018-02-02 06:25
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/.github/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

I am sorry that I have to close this issue here as GitHub does not support moving issues from one project to another.

**Closed by sebastianbergmann** 2018-02-02 06:25 UTC

**Comment by sebastianbergmann** [comment] 2018-02-02 06:29
That being said, I cannot reproduce this:
```
$ ll /tmp/does-not-exist                                               
ls: cannot access '/tmp/does-not-exist': No such file or directory

$ ./vendor/bin/phpunit --coverage-clover /tmp/does-not-exist/clover.xml
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.2 with Xdebug 2.6.0
Configuration: /home/sb/thePHP.cc/terraforming/phpunit.xml

................................                                  32 / 32 (100%)

Time: 74 ms, Memory: 6.00MB

OK (32 tests, 42 assertions)

Generating code coverage report in Clover XML format ... done

$ ll /tmp/does-not-exist                                               
total 12K
-rw-r--r--. 1 sb sb 8,1K  2. Feb 07:28 clover.xml
```

**Comment by KanDisheng** [comment] 2018-02-02 06:50
Try /tmp/does-not-exist-1/does-not-exist-2
