### ISSUE TITLE
No more backtrace when using PHAR

### ISSUE THREAD

**Issue by theredled** [sebastianbergmann/phpunit#4594] opened 2021-01-26 16:04 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.1
| PHP version         | 7.4.13
| Installation Method | PHAR

#### Summary

I don't have any backtrace anymore, all lines are filtered out in `Filter::shouldPrintFrame`.

It seems "logical" to me, as `Filter::getFilteredStacktrace` calls `Filter::shouldPrintFrame` with `__PHPUNIT_PHAR_ROOT__` as a `$prefix` parameter.
But in `Filter::shouldPrintFrame`, a non-empty `$prefix` leads to an always-false return value at line 76 :
```
return $prefix === null && self::fileIsExcluded($file, $excludeList) && \is_file($file);
```
Therefore all lines are ignored.

#### Current behavior

I don't have any backtrace anymore, whatever error level it is.

#### How to reproduce

Produce an error or simply a failed assertion.

#### Expected behavior

Having a backtrace to debug the problem.

**Comment by sebastianbergmann** [comment] 2021-01-27 06:07
Duplicate of #4573.

**Closed by sebastianbergmann** 2021-01-27 06:07 UTC
Labels: type/bug
