### ISSUE TITLE
Can't set up data for dataProvider in phpunit

### ISSUE THREAD

**Issue by tuandigitech** [sebastianbergmann/phpunit#1730] opened 2015-05-27 05:29 UTC
My issue is I can't set up a dynamic data inside dataProvider function. 
I need to set up dataProvider for testing request to an api.
A few data must got from a response of another api. 
However, dataProvider is alway run before setUpBeforeClass function, therefore, I can't find a way to get data first (by request and receive in response of another api) for setting up for dataProvider. 
If I request to api for getting response inside dataProvider function, it will have to request many time incase dataProvider have a lot of case data. 

Is there another solution to solve it in phpunit ?

**Comment by giorgiosironi** [comment] 2015-05-27 19:17
Seems to be a known limitation, check https://github.com/sebastianbergmann/phpunit/issues/836

**Comment by sebastianbergmann** [comment] 2015-06-02 07:14
Duplicate of #836, sorry.

**Closed by sebastianbergmann** 2015-06-02 07:14 UTC
