### ISSUE TITLE
PHPUnit 9 PHAR is not executable on PHP 8.1.0beta1 docker images

### ISSUE THREAD

**Issue by hollodotme** [sebastianbergmann/phpunit#4744] opened 2021-07-24 10:35 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.7
| PHP version         | 8.1.0beta1
| Installation Method | PHAR

#### Summary

**Disclaimer:** I am not sure if this is a PHPUnit issue or a PHP 8.1 Beta version issue. But I wanted to leave it here to raise awareness and just in case you need to adjust something on your end. 😄 

The latest PHPUnit PHAR is not executable on PHP 8.1.0beta1 docker images.

#### Current behavior

When executing the `phpunit.phar` on the latest PHP 8.1.0beta1 docker images I see:

```
Fatal error: Could not check compatibility between PHPUnit\PharIo\Manifest\AuthorCollection::getIterator(): PHPUnit\PharIo\Manifest\AuthorCollectionIterator and IteratorAggregate::getIterator(): Traversable, because class PHPUnit\PharIo\Manifest\AuthorCollectionIterator is not available in phar:///tools/phpunit-9.phar/phar-io-manifest/values/AuthorCollection.php on line 33
```

Running the same on PHP 8.0 prints the help page of PHPUnit as expected.

As far as I could inspect the PHAR file, the class mentioned in the error is there and in the correct directory and namespace.

#### How to reproduce

```bash
# 1. get the PHAR
wget https://phar.phpunit.de/phpunit-9.phar 

# 2. Make it executable
chmod +x phpunit-9.phar

# 3. Run it
docker run --rm -v $(pwd):/tools php:8.1.0beta1-cli /tools/phpunit-9.phar
```

I also tried the following image variants:

* php:8.1.0beta1-fpm
* php:8.1.0beta1-fpm-alpine
* php:8.1.0beta1-cli-alpine

with the same result.

Using latest PHP 8.0 images work, for example:

```bash
docker run --rm -v $(pwd):/tools php:8.0-cli /tools/phpunit-9.phar
```

#### Expected behavior

Seeing the help page of PHPUnit.

**Comment by sebastianbergmann** [comment] 2021-07-24 12:01
Duplicate of #4740.

**Closed by sebastianbergmann** 2021-07-24 12:01 UTC
Labels: type/bug
