### ISSUE TITLE
Fatal error: Uncaught Error: Class 'PHP_Token_DECLARE' not found

### ISSUE THREAD

**Issue by MP-okui** [sebastianbergmann/phpunit#4655] opened 2021-04-21 04:34 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.5.15
| PHP Token Stream  | 4.0.4
| PHP version         | 7.3.23
| Installation Method | Composer

#### Summary

Adding a code coverage option will fail.

#### Current behavior

```sh
> vendor/bin/phpunit --coverage-xml ./coverage --debug
PHPUnit 8.5.15 by Sebastian Bergmann and contributors.

Fatal error: Uncaught Error: Class 'PHP_Token_DECLARE' not found in /var/www/html/vendor/phpunit/php-token-stream/src/Stream.php:477
Stack trace:
#0 /var/www/html/vendor/phpunit/php-token-stream/src/Stream.php(113): PHP_Token_Stream->scan('<?php\n\ndeclare(...')  
#1 /var/www/html/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(638): PHP_Token_Stream->__construct('<?php\n\ndeclare(...')
#2 /var/www/html/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(615): SebastianBergmann\CodeCoverage\CodeCoverage->getLinesToBeIgnoredInner('/var/www/html/s...')
#3 /var/www/html/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(556): SebastianBergmann\CodeCoverage\CodeCoverage->getLinesToBeIgnored('/var/www/html/s...')
#4 /var/www/html/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(299): SebastianBergmann\CodeCoverage\CodeCoverage->applyIgnoredLinesFilter(Array)
#5 /var/www/html/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(975): SebastianBergmann\CodeCoverage\CodeCoverage->append(Array, 'UNCOVERED_FILES...') in /var/www/html/vendor/phpunit/php-token-stream/src/Stream.php on line 477
```

#### How to reproduce

add `--coverage-***` option.

#### Expected behavior

Expect code coverage output.

**Comment by sebastianbergmann** [comment] 2021-04-21 05:02
I cannot reproduce this: https://github.com/sebastianbergmann/phpunit/runs/2387566677?check_suite_focus=true

**Comment by sebastianbergmann** [comment] 2021-04-23 07:27
No feedback, closing.

**Closed by sebastianbergmann** 2021-04-23 07:27 UTC
Labels: type/bug
